import test from 'node:test';import assert from 'node:assert/strict';import {mkdirSync,mkdtempSync} from 'node:fs';import {join,resolve} from 'node:path';mkdirSync('test-data',{recursive:true});process.env.DATA_DIR=mkdtempSync(join(resolve('test-data'),'gemini-'));const {saveSecret}=await import('../server/store.mjs');const {normalizeModel,listModels,requestProvider}=await import('../server/ai-provider.mjs');saveSecret('bot-ai:qa',{token:'private-key-for-test'});
test('Gemini model uses API ID and strips resource prefix',()=>{assert.equal(normalizeModel('gemini','models/gemini-test-flash'),'gemini-test-flash');assert.throws(()=>normalizeModel('gemini','Gemini 3.6'),/mã API/);});
test('Gemini request authenticates by header, ignores OpenAI project fields and thinking',async()=>{const text=await requestProvider({id:'qa',provider:'gemini',model:'models/gemini-test-flash',projectId:'email@example.test',organizationId:'123'},'OK',async(url,opt)=>{assert.equal(url,'https://generativelanguage.googleapis.com/v1beta/models/gemini-test-flash:generateContent');assert.equal(opt.headers['x-goog-api-key'],'private-key-for-test');assert.equal(opt.headers['OpenAI-Organization'],undefined);assert.equal(JSON.parse(opt.body).contents[0].parts[0].text,'OK');return Response.json({candidates:[{content:{parts:[{thought:true,text:'reasoning'},{text:'OK'}]}}]});});assert.equal(text,'OK');});
test('Provider errors show useful reason and never disclose key',async()=>{await assert.rejects(requestProvider({id:'qa',provider:'gemini',model:'gemini-test'},'test',async()=>Response.json({error:{message:'Invalid private-key-for-test'}},{status:400})),e=>e.status===400&&e.message.includes('Invalid')&&!e.message.includes('private-key-for-test'));});
test('Lists Gemini generateContent models across pages, filters embedding-only',async()=>{let n=0;const result=await listModels('gemini','key',async url=>{n++;if(n===1)return Response.json({models:[{name:'models/gemini-test-flash',displayName:'Test',supportedGenerationMethods:['generateContent']},{name:'models/embedding',supportedGenerationMethods:['embedContent']}],nextPageToken:'next'});assert.equal(url.searchParams.get('pageToken'),'next');return Response.json({models:[{name:'models/gemini-next',supportedGenerationMethods:['generateContent']}]});});assert.equal(result.length,2);assert.equal(n,2);assert.ok(result.every(m=>!m.id.startsWith('models/')));});
test('Empty blocked response reports safety reason',async()=>{await assert.rejects(requestProvider({id:'qa',provider:'gemini',model:'gemini-test'},'test',async()=>Response.json({promptFeedback:{blockReason:'SAFETY'}})),/SAFETY/);});

test('Zero quota distinguishes unavailable allowance from exhausted usage',async()=>{for(const error of [{message:'Quota exceeded: limit: 0'},{message:'Resource exhausted',details:[{violations:[{quotaValue:'0'}]}]}])await assert.rejects(requestProvider({id:'qa',provider:'gemini',model:'gemini-test'},'test',async()=>Response.json({error},{status:429})),e=>e.status===429&&e.message.includes('chưa thể kết luận')&&e.message.includes('Antigravity'));});
test('Nonzero rate limit explains model and project dimensions',async()=>{await assert.rejects(requestProvider({id:'qa',provider:'gemini',model:'gemini-test'},'test',async()=>Response.json({error:{message:'Quota exceeded: limit: 20'}},{status:429})),e=>e.status===429&&e.message.includes('RPM, TPM hoặc RPD')&&!e.message.includes('hạn mức bằng 0'));});
