import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,mkdirSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {createHmac} from 'node:crypto';
mkdirSync('test-data',{recursive:true});const dir=mkdtempSync(join(resolve('test-data'),'care-'));const base='http://127.0.0.1:4400';let child,cookie='',csrf='';
async function req(path,method='GET',body,status=200){const r=await fetch(base+'/api'+path,{method,headers:{Cookie:cookie,'Content-Type':'application/json','X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();assert.equal(r.status,status,JSON.stringify(d));if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];if(d.csrf)csrf=d.csrf;return d;}
test('Taophacdo: canonical data, customer journey, team scope and social intake',async t=>{
 child=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,PORT:'4400',DATA_DIR:dir},stdio:'pipe',windowsHide:true});t.after(()=>child.kill());let ready=false;for(let i=0;i<60;i++){try{await fetch(base+'/api/health');ready=true;break;}catch{await new Promise(r=>setTimeout(r,100));}}assert.ok(ready);
 await req('/setup','POST',{name:'Care QA',email:'care@example.test',password:'CareTest2026!',demo:true});
 const canonical={id:'7bc854dc-326a-4d78-a153-8b4d7fdfd9dd',customer_id:'C17700001',customer_name:'Nguyễn An',sdt:'0901234567',email:'an@example.test',dia_chi:'Hà Nội',token:'SENSITIVE-LEARNER-TOKEN',note:'SENSITIVE-HEALTH',raw_backup:{secret:'NEVER-IMPORT'},san_pham:[{id_sp:'SP01',ten_sp:'Giáo trình',so_luong:1,secret:'NESTED-SECRET'}],video_date:'2026-10-01',ma_vd:'T1',is_customized:false};
 await t.test('preview does not mutate, import preserves canonical keys and excludes private fields',async()=>{await req('/taophacdo/import-json','POST',{table:'customers',rows:[canonical],preview:true});assert.ok(!(await req('/state')).customers.some(c=>c.id===canonical.id));await req('/taophacdo/import-json','POST',{table:'customers',rows:[canonical],preview:false});const s=await req('/state'),c=s.customers.find(c=>c.id===canonical.id);assert.equal(c.customer_id,'C17700001');assert.equal(c.phone,canonical.sdt);assert.equal(c.name,canonical.customer_name);assert.ok(!JSON.stringify(s).includes('SENSITIVE'));assert.ok(!JSON.stringify(s).includes('NESTED-SECRET'));assert.ok(!JSON.stringify(s).includes('NEVER-IMPORT'));});
 await t.test('hybrid plan filters master batch/group then custom text customer_id',async()=>{await req('/taophacdo/import-json','POST',{table:'master_video_tasks',preview:false,rows:[{id:'m1',video_date:'2026-10-01',nhom:'T1',day:1,title:'Đúng nhóm',sort_order:0},{id:'m2',video_date:'2026-10-01',nhom:'T2',day:1,title:'Sai nhóm'}]});let p=await req('/care/customers/'+canonical.id+'/plan');assert.deepEqual(p.tasks.map(t=>t.id),['m1']);await req('/taophacdo/import-json','POST',{table:'customers',rows:[{...canonical,is_customized:true}],preview:false});await req('/taophacdo/import-json','POST',{table:'customer_tasks',preview:false,rows:[{id:'ct1',customer_id:canonical.customer_id,day:2,title:'Riêng',is_deleted:false},{id:'ct2',customer_id:canonical.customer_id,day:1,title:'Đã xóa',is_deleted:true},{id:'ct3',customer_id:'OTHER',day:1,title:'Khách khác'}]});p=await req('/care/customers/'+canonical.id+'/plan');assert.deepEqual(p.tasks.map(t=>t.id),['ct1']);});
 let conv,order,course;
 await t.test('phone detection creates attributed lead; notes do not satisfy response SLA',async()=>{conv=await req('/conversations/demo','POST',{connectionId:'ch1',customerId:canonical.id,kind:'comment',text:'Tư vấn cho mình qua +84 901 234 567'});let s=await req('/state');assert.equal(s.leads.filter(l=>l.conversationId===conv.id).length,1);assert.equal(s.leads.find(l=>l.conversationId===conv.id).phone,'0901234567');assert.ok(s.conversations.find(c=>c.id===conv.id).waitingSince);await req('/conversations/'+conv.id+'/messages','POST',{text:'Nhân viên cần gọi',note:true,version:conv.version});s=await req('/state');let c=s.conversations.find(c=>c.id===conv.id);assert.ok(c.waitingSince);await req('/conversations/'+conv.id+'/messages','POST',{text:'Chào bạn',version:c.version});c=(await req('/state')).conversations.find(c=>c.id===conv.id);assert.equal(c.waitingSince,null);});
 await t.test('unpaid journey cannot move to paid or active',async()=>{await req('/care/customers/'+canonical.id+'/journey','POST',{stage:'DONG_TIEN'},400);await req('/care/customers/'+canonical.id+'/journey','POST',{stage:'DANG_HOC',startDate:'2026-10-01',endDate:'2026-11-01'},400);});
 await t.test('course sale creates canonical payment payload and does not reserve inventory',async()=>{course=await req('/care/courses','POST',{name:'Yoga cơ bản',fee:1000000,duration:'30 ngày'});let s=await req('/state');const p=s.products.find(p=>p.courseId===course.id);order=await req('/orders','POST',{customerId:canonical.id,conversationId:conv.id,items:[{productId:p.id,quantity:1}],shippingFee:30000});assert.equal(order.total,1000000);assert.equal(order.requiresShipping,false);await req('/orders/'+order.id+'/action','POST',{action:'confirm'});s=await req('/state');assert.equal(s.products.find(x=>x.id===p.id).reserved,0);assert.equal(s.payment_orders.find(o=>o.orderId===order.id).customer_id,canonical.customer_id);await req('/orders/'+order.id+'/shipments','POST',{carrier:'demo'},400);await req('/orders/'+order.id+'/action','POST',{action:'pay',amount:1000000,reference:'QA verified transfer'});s=await req('/state');assert.equal(s.enrollments.filter(e=>e.orderId===order.id).length,1);assert.equal(s.payment_orders.find(o=>o.orderId===order.id).order_payload.paid,1000000);});
 await t.test('paid journey checks dates and version; lead won needs confirmed order',async()=>{let j=await req('/care/customers/'+canonical.id+'/journey','POST',{stage:'DONG_TIEN'});await req('/care/customers/'+canonical.id+'/journey','POST',{stage:'DANG_HOC',version:j.version,startDate:'2026-11-01',endDate:'2026-10-01'},400);j=await req('/care/customers/'+canonical.id+'/journey','POST',{stage:'DANG_HOC',version:j.version,startDate:'2026-10-01',endDate:'2026-11-01'});await req('/care/customers/'+canonical.id+'/journey','POST',{stage:'DA_XONG',version:j.version-1},409);const l=(await req('/state')).leads.find(l=>l.customerId===canonical.id);await req('/care/leads/'+l.id,'PATCH',{stage:'LOST',version:l.version},400);await req('/care/leads/'+l.id,'PATCH',{stage:'WON',version:l.version});});
 await t.test('team members cannot read or mutate unrelated customer via guessed ID',async()=>{const u=await req('/users','POST',{name:'Support',email:'support@example.test',password:'Support2026!',role:'support'});await req('/care/teams','POST',{name:'Nhóm Page',userIds:[u.id],connectionIds:['ch1']});const ownerCookie=cookie,ownerCsrf=csrf;await req('/login','POST',{email:'support@example.test',password:'Support2026!'});const s=await req('/state');assert.deepEqual(s.connections.map(c=>c.id),['ch1']);assert.ok(s.customers.some(c=>c.id===canonical.id));assert.ok(!s.conversations.some(c=>c.connectionId==='ch2'));await req('/records/customers/c2','PATCH',{name:'Không được sửa'},403);await req('/taophacdo/import-json','POST',{table:'customers',rows:[]},403);cookie=ownerCookie;csrf=ownerCsrf;});
 await t.test('webhook signature rejection and comment dedupe preserve a single lead',async()=>{const ch=await req('/records/connections','POST',{name:'Webhook QA',provider:'facebook',mode:'api',accountId:'PAGE-QA',apiVersion:'v25.0',appSecret:'ONLY-TEST-SECRET'});const payload={entry:[{id:'PAGE-QA',time:123,changes:[{field:'feed',value:{item:'comment',verb:'add',comment_id:'COMMENT-QA',post_id:'POST-QA',message:'Gọi tôi 0987654321',from:{id:'PERSON-QA',name:'Khách QA'},created_time:123}}]}]};const raw=JSON.stringify(payload),signature='sha256='+createHmac('sha256','ONLY-TEST-SECRET').update(raw).digest('hex');let r=await fetch(base+'/api/webhooks/'+ch.id,{method:'POST',body:raw});assert.equal(r.status,403);for(let i=0;i<2;i++){r=await fetch(base+'/api/webhooks/'+ch.id,{method:'POST',headers:{'x-hub-signature-256':signature},body:raw});assert.equal(r.status,200);}const s=await req('/state');const cs=s.conversations.filter(c=>c.externalCommentId==='COMMENT-QA');assert.equal(cs.length,1);assert.equal(s.messages.filter(m=>m.conversationId===cs[0].id).length,1);assert.equal(s.leads.filter(l=>l.conversationId===cs[0].id).length,1);});
 await t.test('schedule requires ten minutes, rejected order does not leave orphan',async()=>{const c=await req('/records/contents','POST',{title:'Lịch gần',caption:'Test',type:'text',channels:['ch1']});await req('/contents/'+c.id+'/schedule','POST',{version:c.version,scheduleAt:new Date(Date.now()+60000).toISOString()},400);const before=(await req('/state')).orders.length;await req('/orders','POST',{customerId:'c1',conversationId:conv.id,items:[{productId:'p1',quantity:1}]},400);assert.equal((await req('/state')).orders.length,before);});
 await t.test('ordered template blocks substitute names and completed runs cannot replay',async()=>{const template=await req('/care/templates','POST',{name:'Tư vấn khóa học',shortcut:'tuvan',blocks:[{text:'Chào {{name}}'},{text:'Bạn muốn tư vấn lịch học nào?'}]});const r=await req('/care/conversations/'+conv.id+'/template','POST',{templateId:template.id});assert.equal(r.status,'done');assert.equal(r.nextIndex,2);const messages=(await req('/state')).messages;assert.equal(messages.find(m=>m.id===r.messageIds[0]).text,'Chào Nguyễn An');await req('/care/conversations/'+conv.id+'/template','POST',{runId:r.id},400);});
 await t.test('refund revokes verified enrollment and blocks paid-stage transition',async()=>{await req('/orders/'+order.id+'/action','POST',{action:'refund',amount:1000000,reference:'QA hoàn toàn bộ'});const s=await req('/state');assert.equal(s.enrollments.find(e=>e.orderId===order.id).paymentVerified,false);const j=s.journeys.find(j=>j.customerId===canonical.id);await req('/care/customers/'+canonical.id+'/journey','POST',{stage:'DONG_TIEN',version:j.version},400);});
 await t.test('support can access own newly created customer without broadening other scope',async()=>{const ownerCookie=cookie,ownerCsrf=csrf;await req('/login','POST',{email:'support@example.test',password:'Support2026!'});const c=await req('/records/customers','POST',{name:'Khách do tôi tạo',phone:'0933333333',tags:[]});const s=await req('/state');assert.ok(s.customers.some(x=>x.id===c.id));await req('/records/customers/'+c.id,'PATCH',{version:c.version,name:'Đã cập nhật'});await req('/records/customers/c2','PATCH',{name:'Vẫn bị chặn'},403);cookie=ownerCookie;csrf=ownerCsrf;});
});
