import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync} from 'node:fs';import {join,resolve} from 'node:path';
mkdirSync('test-data',{recursive:true});process.env.DATA_DIR=mkdtempSync(join(resolve('test-data'),'tags-mentions-'));process.env.PLAN_REMOTE_CATALOG='0';
const {put,get,all,db}=await import('../server/store.mjs');const {tagRoute}=await import('../server/conversation-tags.mjs');const {reply}=await import('../server/domain.mjs');const {validateGroupMentions}=await import('../server/group-mentions.mjs');const {reconcileMentions}=await import('../public/group-mention-model.js');
const owner={id:'owner',role:'owner'},support={id:'support',role:'support'};
test('tag management requires manager and preserves assignments when renamed',()=>{assert.throws(()=>tagRoute('/api/care/tags','POST',{},support),{status:403});const tag=tagRoute('/api/care/tags','POST',{name:'Tag cũ',color:'#123456',sortOrder:2,description:'Mô tả'},owner);put('conversations',{id:'tag-conv',tags:[tag.name]});const next=tagRoute('/api/care/tags','POST',{id:tag.id,version:tag.version,name:'Tag mới',color:'#654321',sortOrder:1,active:false},owner);assert.equal(next.active,false);assert.deepEqual(get('conversations','tag-conv').tags,['Tag mới']);assert.throws(()=>tagRoute('/api/care/tags','POST',{id:tag.id,version:tag.version,name:'stale',color:'#654321'},owner),{status:409});assert.throws(()=>tagRoute('/api/care/tags','POST',{name:'tag mới',color:'#654321'},owner),{status:400});tagRoute('/api/care/tags/bulk','POST',{action:'delete',items:[{id:next.id,version:next.version}]},owner);assert.equal(get('tags',tag.id),null);assert.deepEqual(get('conversations','tag-conv').tags,[]);});
test('bulk tag updates roll back entirely on revision conflict',()=>{const a=put('tags',{name:'A',color:'#123456'}),b=put('tags',{name:'B',color:'#123456'});assert.throws(()=>tagRoute('/api/care/tags/bulk','POST',{action:'stop',items:[{id:a.id,version:a.version},{id:b.id,version:0}]},owner),{status:409});assert.notEqual(get('tags',a.id).active,false);});
test('group mentions reject forged members, changed labels and invalid ranges',()=>{const c={threadType:1,group:{members:[{id:'123',name:'Hà'}]}},text='😀 @Hà xin chào',m={uid:'123',pos:3,len:3};assert.deepEqual(validateGroupMentions(c,text,[m]),[m]);assert.throws(()=>validateGroupMentions(c,text,[{...m,uid:'456'}]),{status:400});assert.throws(()=>validateGroupMentions(c,text,[{...m,pos:0}]),{status:400});assert.throws(()=>validateGroupMentions({...c,threadType:0},text,[m]),{status:400});assert.throws(()=>validateGroupMentions(c,text,{}),{status:400});});
test('draft mention offsets shift when edited and disappear if the name is changed',()=>{const m={uid:'123',pos:0,len:3,text:'@Hà'};assert.equal(reconcileMentions('@Hà hi','😀 @Hà hi',[m])[0].pos,3);assert.deepEqual(reconcileMentions('@Hà hi','@Ha hi',[m]),[]);});
test('reply stores mention metadata and shifts offsets after trimming and quoted prefix',async()=>{db.prepare('INSERT INTO users(id,email,name,role,password) VALUES(?,?,?,?,?)').run('owner','tags@example.test','Owner','owner','test-only');put('connections',{id:'demo-mention',mode:'demo'});const c=put('conversations',{id:'group-mention',connectionId:'demo-mention',customerId:'c',threadType:1,group:{members:[{id:'123',name:'Hà'}]}});const quote=put('messages',{conversationId:c.id,direction:'incoming',text:'Câu hỏi'});const result=await reply(owner,c.id,{text:'  @Hà xin chào',quoteId:quote.id,mentions:[{uid:'123',pos:2,len:3}],version:c.version});assert.equal(result.text.slice(result.mentions[0].pos,result.mentions[0].pos+3),'@Hà');assert.equal(result.status,'demo');});
