import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtempSync,readFileSync,existsSync } from 'node:fs';
import { resolve,join } from 'node:path';
import { mkdirSync } from 'node:fs';
const root=resolve('test-data');mkdirSync(root,{recursive:true});const dataDir=mkdtempSync(join(root,'api-'));
const port=4399;let child,cookie='',csrf='';
const base=`http://127.0.0.1:${port}`;
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function start(){child=spawn(process.execPath,['server/index.mjs'],{cwd:process.cwd(),env:{...process.env,PORT:String(port),DATA_DIR:dataDir},stdio:['ignore','pipe','pipe'],windowsHide:true});let logs='';child.stdout.on('data',x=>logs+=x);child.stderr.on('data',x=>logs+=x);for(let i=0;i<40;i++){try{const r=await fetch(base+'/api/health');if(r.ok)return;}catch{}await pause(100);}throw new Error(logs);}
async function stop(){if(child&&!child.killed){child.kill();await new Promise(r=>child.once('exit',r));}}
async function req(path,method='GET',body,expect=200,key){const res=await fetch(base+'/api'+path,{method,headers:{'Content-Type':'application/json',Cookie:cookie,'X-CSRF-Token':csrf,...(key?{'Idempotency-Key':key}:{})},body:body===undefined?undefined:JSON.stringify(body)});const data=await res.json();assert.equal(res.status,expect,JSON.stringify(data));const sc=res.headers.get('set-cookie');if(sc)cookie=sc.split(';')[0];if(data.csrf)csrf=data.csrf;return data;}
test('Local application: persistence, scheduling, inventory, COD, access control and webhook dedupe',async t=>{await start();t.after(stop);
 await t.test('bootstrap and secure owner setup',async()=>{assert.equal((await req('/bootstrap')).setup,true);await req('/setup','POST',{name:'QA Owner',workspace:'QA workspace',email:'qa@example.test',password:'OnlyForLocalTests2026!',demo:true});assert.equal((await req('/state')).products.length,4);await req('/setup','POST',{},409);});
 let content,customer,product,order,shipment;
 await t.test('draft persistence and revision conflicts',async()=>{content=await req('/records/contents','POST',{title:'Kiểm thử lịch',caption:'Nội dung mẫu',type:'text',channels:['ch1'],assets:[]});const saved=await req('/records/contents/'+content.id,'PATCH',{title:'Lịch đã sửa',version:content.version});await req('/records/contents/'+content.id,'PATCH',{title:'Ghi đè lỗi',version:content.version},409);content=saved;});
 await t.test('idempotent scheduler and demo does not claim a real publication',async()=>{const b={version:content.version,immediate:true};const first=await req(`/contents/${content.id}/schedule`,'POST',b,200,'same-schedule');const second=await req(`/contents/${content.id}/schedule`,'POST',b,200,'same-schedule');assert.equal(first[0].id,second[0].id);await pause(5400);const state=await req('/state');assert.equal(state.publications.find(p=>p.id===first[0].id).status,'demo_published');});
 await t.test('manual publication only confirms with valid URL',async()=>{const conn=await req('/records/connections','POST',{name:'Hỗ trợ',provider:'facebook_personal',mode:'assisted'});const c=await req('/records/contents','POST',{title:'Thủ công',caption:'Caption',type:'text',channels:[conn.id]});const [p]=await req(`/contents/${c.id}/schedule`,'POST',{version:c.version,immediate:true});await pause(5200);assert.equal((await req('/state')).publications.find(x=>x.id===p.id).status,'awaiting_manual');await req(`/publications/${p.id}/action`,'POST',{action:'confirm',url:'javascript:alert(1)'},400);await req(`/publications/${p.id}/action`,'POST',{action:'confirm',url:'https://example.com/test'});});
 await t.test('create SKU and customer with server side price authority',async()=>{customer=await req('/records/customers','POST',{name:'Khách kiểm thử',phone:'0900000111',address:'Địa chỉ mẫu',tags:[]});product=await req('/records/products','POST',{name:'SKU cuối',sku:'QA-LAST',price:100000,cost:50000,stock:1,weight:100});order=await req('/orders','POST',{customerId:customer.id,items:[{productId:product.id,quantity:1,price:1}],shippingFee:20000});assert.equal(order.total,120000);});
 await t.test('prevent overselling and double confirmation',async()=>{const other=await req('/orders','POST',{customerId:customer.id,items:[{productId:product.id,quantity:1}],shippingFee:20000});const results=await Promise.all([fetch(base+`/api/orders/${order.id}/action`,{method:'POST',headers:{Cookie:cookie,'X-CSRF-Token':csrf,'Content-Type':'application/json'},body:JSON.stringify({action:'confirm'})}),fetch(base+`/api/orders/${other.id}/action`,{method:'POST',headers:{Cookie:cookie,'X-CSRF-Token':csrf,'Content-Type':'application/json'},body:JSON.stringify({action:'confirm'})})]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);const state=await req('/state');order=state.orders.find(o=>[order.id,other.id].includes(o.id)&&o.status==='confirmed');assert.equal(state.products.find(p=>p.id===product.id).reserved,1);await req(`/orders/${order.id}/action`,'POST',{action:'confirm'},400);});
 await t.test('shipment creation and dispatch change stock once',async()=>{shipment=await req(`/orders/${order.id}/shipments`,'POST',{carrier:'demo',fee:20000},200,'shipment-once');assert.equal((await req(`/orders/${order.id}/shipments`,'POST',{carrier:'demo',fee:20000},200,'shipment-once')).id,shipment.id);await req(`/orders/${order.id}/shipments`,'POST',{carrier:'demo'},400);await req(`/shipments/${shipment.id}/action`,'POST',{status:'in_transit'});const state=await req('/state');const p=state.products.find(p=>p.id===product.id);assert.equal(p.stock,0);assert.equal(p.reserved,0);await req(`/shipments/${shipment.id}/action`,'POST',{status:'in_transit'},400);});
 await t.test('delivery does not automatically settle COD; discrepancy is not income',async()=>{await req(`/shipments/${shipment.id}/action`,'POST',{status:'delivered'});assert.equal((await req('/state')).orders.find(o=>o.id===order.id).paid,0);await req(`/shipments/${shipment.id}/action`,'POST',{action:'settle',amount:1});assert.equal((await req('/state')).orders.find(o=>o.id===order.id).paid,0);await req(`/shipments/${shipment.id}/action`,'POST',{action:'settle',amount:100000});assert.equal((await req('/state')).orders.find(o=>o.id===order.id).paid,120000);await req(`/shipments/${shipment.id}/action`,'POST',{action:'settle',amount:100000},400);});
 await t.test('return quantity validation and no automatic refund',async()=>{await req(`/orders/${order.id}/action`,'POST',{action:'return',reason:'Đã kiểm tra',items:[{productId:product.id,quantity:1,restock:true}]});const s=await req('/state');assert.equal(s.products.find(p=>p.id===product.id).stock,1);assert.equal(s.orders.find(o=>o.id===order.id).paid,120000);await req(`/orders/${order.id}/action`,'POST',{action:'return',reason:'Lặp',items:[{productId:product.id,quantity:1,restock:true}]},400);});
 await t.test('inbox reply is revision checked and explicitly a demo',async()=>{const conv=await req('/conversations/demo','POST',{connectionId:'ch1',customerId:customer.id,text:'Cho mình hỏi giá?'});const state=await req('/state');const latest=state.conversations.find(c=>c.id===conv.id);assert.ok(latest.tags.includes('Hỏi giá'));const msg=await req(`/conversations/${conv.id}/messages`,'POST',{text:'Chào bạn',version:latest.version});assert.equal(msg.status,'demo');await req(`/conversations/${conv.id}/messages`,'POST',{text:'Lặp',version:latest.version},409);});
 await t.test('secrets never exported in state and read permissions enforced',async()=>{await req('/records/connections','POST',{name:'Chưa có quyền',provider:'facebook',mode:'api',accountId:'test',apiVersion:'v25.0',token:'NEVER-EXPOSE-ME',appSecret:'NEVER-APP-SECRET',verifyToken:'NEVER-VERIFY-TOKEN'});const state=JSON.stringify(await req('/state'));assert.ok(!state.includes('NEVER-'));const ownerCookie=cookie,ownerCsrf=csrf;await req('/users','POST',{name:'Viewer',email:'viewer@example.test',password:'ViewerTestPassword!',role:'viewer'});await req('/login','POST',{email:'viewer@example.test',password:'ViewerTestPassword!'});await req('/records/products','POST',{name:'forbidden'},403);await req('/export','GET',undefined,403);cookie=ownerCookie;csrf=ownerCsrf;});
 await t.test('CSRF and unauthenticated reads rejected',async()=>{let r=await fetch(base+'/api/orders',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json'},body:'{}'});assert.equal(r.status,403);r=await fetch(base+'/api/state');assert.equal(r.status,401);});
 await t.test('backup and export exclude auth records',async()=>{const b=await req('/backup','POST',{});assert.ok(existsSync(join(dataDir,'backups',b.name)));const ex=await req('/export');assert.equal(ex.version,1);assert.ok(!JSON.stringify(ex).includes('OnlyForLocalTests2026!'));});
 await t.test('restart preserves database and schedule state',async()=>{await stop();await start();const state=await req('/state');assert.ok(state.orders.some(o=>o.id===order.id));assert.equal(state.products.find(p=>p.id===product.id).stock,1);});
});
