import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdirSync,mkdtempSync} from 'node:fs';import {resolve,join} from 'node:path';
mkdirSync('test-data',{recursive:true});const dir=mkdtempSync(join(resolve('test-data'),'learner-')),base='http://127.0.0.1:4423';let cookie='',csrf='';
async function req(path,method='GET',body,status=200){const r=await fetch(base+'/api'+path,{method,headers:{Cookie:cookie,'X-CSRF-Token':csrf,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();assert.equal(r.status,status,JSON.stringify(d));if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];if(d.csrf)csrf=d.csrf;return d;}
test('Learner profile, renewals and quick orders preserve identity and payments',async t=>{const child=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,PORT:'4423',DATA_DIR:dir,PLAN_REMOTE_CATALOG:'0'},stdio:'pipe',windowsHide:true});t.after(()=>child.kill());for(let n=0;n<60;n++){try{await fetch(base+'/api/health');break;}catch{await new Promise(r=>setTimeout(r,100));}}
 await req('/setup','POST',{name:'Owner',email:'learner@example.test',password:'LearnerTest2026!',demo:true});const c=await req('/records/customers','POST',{name:'Học viên',phone:'0901234567'}),course=await req('/care/courses','POST',{name:'Khóa học Face Yoga',fee:500000,duration:'30 ngày'}),product=(await req('/state')).products.find(p=>p.courseId===course.id),order=await req('/orders','POST',{customerId:c.id,items:[{productId:product.id,quantity:1}]});await req('/orders/'+order.id+'/action','POST',{action:'pay',amount:500000,reference:'Đã đối soát'});const h=await req('/plans/prepare','POST',{orderId:order.id}),editor=await req('/plans/'+h.id+'/editor');await req('/plans/'+h.id+'/save','POST',{version:0,customer:{...editor.customer,start_date:'2026-10-01',duration_days:30,is_customized:true},tasks:[{day:1,title:'Bài tập 1',link:'https://example.test/video'},{day:2,title:'Bài tập 2',link:'https://example.test/video2'}]});
 const path='/care/customers/'+c.id+'/learner';let profile=await req(path);const update=async data=>{profile=await req(path,'PATCH',{...data,customerVersion:profile.customer.version,version:profile.version});return profile;};
 await t.test('loads plan dates, security and purchases without tokens',async()=>{assert.equal(profile.plan.startDate,'2026-10-01');assert.equal(profile.attendance.total,2);assert.equal(profile.purchases.total,500000);assert.equal(profile.plan.googleAuth,true);assert.ok(!JSON.stringify(profile).includes('token'));});
 await t.test('validates calendar dates and conflicting revisions',async()=>{await req(path,'PATCH',{action:'dates',customerVersion:profile.customer.version,version:profile.version,startDate:'2026-02-30',endDate:'2026-12-01'},400);await req(path,'PATCH',{action:'security',customerVersion:0,version:profile.version,googleAuth:false,deviceLimit:false},409);await update({action:'dates',startDate:'2026-10-02',endDate:'2026-11-02'});assert.equal(profile.plan.durationDays,31);});
 await t.test('security and explicit stage changes persist',async()=>{await update({action:'security',googleAuth:false,deviceLimit:true});assert.equal(profile.plan.googleAuth,false);await update({action:'stage',stage:'CONSULTED'});assert.equal(profile.stage,'CONSULTED');});
 await t.test('renewal fee adds to the course without fabricating a payment or revoking paid access',async()=>{await update({action:'renew',baseDate:'2026-11-02',days:30,amount:120000});assert.equal(profile.plan.endDate,'2026-12-02');const o=(await req('/state')).orders.find(o=>o.id===order.id);assert.equal(o.items[0].price,620000);assert.equal(o.total,620000);assert.equal(o.paid,500000);assert.equal(o.paymentStatus,'partial');assert.notEqual((await req('/state')).chatPlanSummaries.find(p=>p.customerId===c.id).status,'REVOKED');await req('/plans/'+h.id+'/editor');await req(path,'PATCH',{action:'renew',baseDate:'2026-10-02',days:1,customerVersion:profile.customer.version,version:profile.version},400);});
 await t.test('refund below original paid access freezes plan',async()=>{await req('/orders/'+order.id+'/action','POST',{action:'refund',amount:1,reference:'Hoàn đã đối soát'});assert.equal((await req('/state')).chatPlanSummaries.find(p=>p.customerId===c.id).status,'REVOKED');await req('/plans/'+h.id+'/editor','GET',undefined,409);await req('/orders/'+order.id+'/action','POST',{action:'pay',amount:1,reference:'Thu lại'});});
 await t.test('copies only plan content into a draft, excluding learner identity',async()=>{const target=await req('/records/customers','POST',{name:'Học viên mới',phone:'0902222222'});await req('/care/customers/'+target.id+'/learner/copy','POST',{sourceId:c.id,customerVersion:target.version});const d=await req('/plans/'+encodeURIComponent('draft:'+target.id)+'/editor');assert.equal(d.customer.customer_name,target.name);assert.equal(d.customer.sdt,target.phone);assert.equal(d.customer.is_customized,true);assert.equal(d.tasks.length,2);assert.equal(d.customer.require_google_auth,false);});
 await t.test('quick order uses editable price and stores transfer intent, no payment',async()=>{const context=await req(path+'/order');assert.ok(context.products.some(p=>p.id===product.id));const result=await req(path+'/order','POST',{name:'Updated Name',customerVersion:profile.customer.version,phone:'0901234567',email:'student@example.test',items:[{productId:product.id,quantity:2,price:400000}],bankTransfer:true,transferAmount:800000,freeShipping:true});assert.equal(result.total,800000);assert.equal(result.paid,0);assert.equal(result.transferAmount,800000);assert.equal(result.items[0].price,400000);profile=await req(path);assert.equal(profile.customer.email,'student@example.test');assert.equal(profile.customer.name,'Updated Name');});
 await t.test('physical quick order saves without address; confirmation waits for customer address',async()=>{const item=await req('/records/products','POST',{name:'Kem mắt QA',sku:'EYE-QA',price:330000,cost:100000,stock:10,productType:'physical'}),context=await req(path+'/order');const result=await req(path+'/order','POST',{customerVersion:context.customer.version,phone:context.customer.phone,items:[{productId:item.id,quantity:1,price:330000},{productId:product.id,quantity:1,price:500000}],freeShipping:true,bankTransfer:true,transferAmount:830000});assert.equal(result.status,'draft');assert.equal(result.address,'');assert.equal(result.total,830000);assert.equal(result.paid,0);await req('/orders/'+result.id+'/action','POST',{action:'confirm'},400);profile=await req(path);await update({action:'contact',address:'Địa chỉ đã bổ sung'});const confirmed=await req('/orders/'+result.id+'/action','POST',{action:'confirm'});assert.equal(confirmed.status,'confirmed');assert.equal(confirmed.address,'Địa chỉ đã bổ sung');});
 await t.test('detects the first incoming phone and never overwrites an existing phone',async()=>{const person=await req('/records/customers','POST',{name:'Khách cung cấp số điện thoại'});await req('/conversations/demo','POST',{connectionId:'ch1',customerId:person.id,text:'Số điện thoại mình là 090 333 4444'});assert.equal((await req('/state')).customers.find(p=>p.id===person.id).phone,'0903334444');await req('/conversations/demo','POST',{connectionId:'ch1',customerId:person.id,text:'Số khác 0905556666'});assert.equal((await req('/state')).customers.find(p=>p.id===person.id).phone,'0903334444');});
 await t.test('unassigned support cannot read or mutate guessed learner IDs',async()=>{await req('/users','POST',{name:'Unassigned',email:'unassigned-learner@example.test',password:'Unassigned2026!',role:'support'});await req('/login','POST',{email:'unassigned-learner@example.test',password:'Unassigned2026!'});await req(path,'GET',undefined,403);await req(path,'PATCH',{action:'security'},403);await req(path+'/sources','GET',undefined,403);});
});
