import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,mkdirSync} from 'node:fs';
import {join,resolve} from 'node:path';
mkdirSync('test-data',{recursive:true});const dir=mkdtempSync(join(resolve('test-data'),'plan-')),base='http://127.0.0.1:4402';let cookie='',csrf='',child;
async function req(path,method='GET',body,status=200){const r=await fetch(base+'/api'+path,{method,headers:{Cookie:cookie,'X-CSRF-Token':csrf,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();assert.equal(r.status,status,JSON.stringify(d));if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];if(d.csrf)csrf=d.csrf;return d;}
test('Paid order to reused PlanEditor workflow bridge',async t=>{
 child=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,PORT:'4402',DATA_DIR:dir},stdio:'pipe',windowsHide:true});t.after(()=>child.kill());for(let i=0;i<60;i++){try{await fetch(base+'/api/health');break;}catch{await new Promise(r=>setTimeout(r,100));}}
 await req('/setup','POST',{name:'Plan QA',email:'plan@example.test',password:'PlanTest2026!',demo:true});const c=await req('/records/customers','POST',{name:'Học viên bridge',phone:'0901234567',email:'bridge@example.test',address:'Hà Nội'});const course=await req('/care/courses','POST',{name:'Yoga 30 ngày',fee:500000,duration:'30 ngày'});const product=(await req('/state')).products.find(p=>p.courseId===course.id);const conv=await req('/conversations/demo','POST',{connectionId:'ch1',customerId:c.id,text:'Mình đăng ký khóa học'});const order=await req('/orders','POST',{customerId:c.id,conversationId:conv.id,items:[{productId:product.id,quantity:1}]});let handoff,editor;
 await t.test('unpaid and deposit orders cannot prepare a plan',async()=>{await req('/plans/prepare','POST',{orderId:order.id},409);await req('/orders/'+order.id+'/action','POST',{action:'confirm'});await req('/orders/'+order.id+'/action','POST',{action:'pay',amount:200000,reference:'Cọc đã đối soát'});await req('/plans/prepare','POST',{orderId:order.id},409);assert.equal((await req('/state')).plan_handoffs.length,0);});
 await t.test('full payment automatically creates one stable handoff and canonical draft',async()=>{await req('/orders/'+order.id+'/action','POST',{action:'pay',amount:300000,reference:'Đã nhận phần còn lại'});let s=await req('/state');assert.equal(s.plan_handoffs.length,1);handoff=s.plan_handoffs[0];assert.equal(handoff.status,'ready');const again=await req('/plans/prepare','POST',{orderId:order.id});assert.equal(again.id,handoff.id);editor=await req('/plans/'+handoff.id+'/editor');assert.equal(editor.customer.customer_name,c.name);assert.equal(editor.customer.sdt,c.phone);assert.equal(editor.customer.gia_tien,500000);assert.equal(editor.customer.customer_id,handoff.canonicalId);assert.equal(editor.customer.token,'');assert.equal(editor.paymentEvidence.length,2);});
 await t.test('save plan preserves paid order and guards dangerous links, version and identity',async()=>{await req('/plans/'+handoff.id+'/save','POST',{version:0,customer:{...editor.customer,customer_id:'WRONG'},tasks:[]},400);await req('/plans/'+handoff.id+'/save','POST',{version:0,customer:{...editor.customer,gia_tien:1},tasks:[]},400);await req('/plans/'+handoff.id+'/save','POST',{version:0,customer:{...editor.customer,is_customized:true},tasks:[{day:1,title:'A',link:'javascript:alert(1)'}]},400);const saved=await req('/plans/'+handoff.id+'/save','POST',{version:0,customer:{...editor.customer,is_customized:true,start_date:'2026-10-01',duration_days:30,note:'Mục tiêu riêng'},tasks:[{day:1,title:'Khởi động',detail:'Thực hiện theo hướng dẫn',link:'https://example.test/video',type:'Bài bắt buộc'}]});assert.equal(saved.end_date,'2026-10-31');assert.equal(saved.planVersion,1);await req('/plans/'+handoff.id+'/save','POST',{version:0,customer:saved,tasks:[]},409);const s=await req('/state');assert.equal(s.plan_handoffs[0].status,'saved_local');assert.ok(s.messages.some(m=>m.handoffId===handoff.id&&m.direction==='note'));assert.equal(s.journeys.find(j=>j.customerId===c.id).stage,'DONG_TIEN');assert.ok(!JSON.stringify(s).includes('Mục tiêu riêng'));});
 await t.test('preview and handoff package retain canonical schema without learner secrets',async()=>{const p=await req('/plans/'+handoff.id+'/preview');assert.equal(p.tasks.length,1);const ex=await req('/plans/'+handoff.id+'/export');assert.equal(ex.schema,'taophacdo.social-handoff.v1');assert.equal(ex.customer.customer_id,handoff.canonicalId);assert.ok(!('token' in ex.customer));assert.ok(!('link' in ex.customer));assert.equal(ex.order.paid,500000);});
 await t.test('refund freezes editor and prevents extra saves without deleting plan',async()=>{await req('/orders/'+order.id+'/action','POST',{action:'refund',amount:1,reference:'Điều chỉnh thu'});assert.equal((await req('/state')).plan_handoffs[0].status,'payment_review');await req('/plans/'+handoff.id+'/editor','GET',undefined,409);await req('/plans/'+handoff.id+'/save','POST',{version:1,customer:editor.customer,tasks:[]},409);await req('/orders/'+order.id+'/action','POST',{action:'pay',amount:1,reference:'Thu lại khoản điều chỉnh'});assert.equal((await req('/state')).plan_handoffs[0].status,'saved_local');assert.equal((await req('/plans/'+handoff.id+'/preview')).tasks.length,1);});
 await t.test('chat can open a new draft without allowing unpaid saves',async()=>{const draftCustomer=await req('/records/customers','POST',{name:'Khách mới từ chat',phone:'0902222222'});const path='/plans/'+encodeURIComponent('draft:'+draftCustomer.id);const d=await req(path+'/editor');assert.equal(d.mode,'unpaid_draft');assert.equal(d.customer.customer_name,draftCustomer.name);assert.equal(d.order.total,0);await req(path+'/save','POST',{customer:d.customer,tasks:[]},409);});
 await t.test('unassigned staff cannot read handoff even with known ID',async()=>{await req('/users','POST',{name:'Unassigned',email:'unassigned@example.test',password:'Unassigned2026!',role:'support'});await req('/login','POST',{email:'unassigned@example.test',password:'Unassigned2026!'});assert.equal((await req('/state')).plan_handoffs.length,0);await req('/plans/'+handoff.id+'/editor','GET',undefined,403);await req('/plans/'+encodeURIComponent('draft:'+c.id)+'/editor','GET',undefined,403);});
});
