import test from 'node:test';
import assert from 'node:assert/strict';
import {publishPlan} from '../server/plan-publish.mjs';
function fixture(){let customer=null,tasks=[];let failTasks=false;const calls=[];return {calls,get customer(){return customer;},get tasks(){return tasks;},fail(){failTasks=true;},request:async(path,init={})=>{calls.push({path,method:init.method||'GET'});const u=new URL(path,'https://test.invalid'),method=init.method||'GET',body=init.body?JSON.parse(init.body):null;
 if(u.pathname.endsWith('/customers')){if(method==='GET')return customer?[structuredClone(customer)]:[];if(method==='DELETE'){customer=null;return null;}if(method==='PATCH'&&u.searchParams.get('updated_at')!==('eq.'+customer?.updated_at))return [];customer={...customer,...body};return [structuredClone(customer)];}
 if(method==='GET')return structuredClone(tasks);if(method==='POST'){if(failTasks)throw new Error('task write failed');tasks.push(...body);return null;}if(method==='DELETE'){const ids=u.searchParams.get('id').slice(4,-1).split(',');tasks=tasks.filter(t=>!ids.includes(t.id));return null;}
 }};}
const profile={customer_id:'C-QA',customer_name:'QA',sdt:'',start_date:'2026-10-07',end_date:'2026-11-06',duration_days:30,video_date:'',trang_thai:0,status:'ACTIVE',is_customized:true,require_google_auth:true,require_device_limit:true,san_pham:[{ten_sp:'Khóa học',so_luong:1,don_gia:500000}],gia_tien:500000,is_consultation:true,is_deposit:false};
test('chat plan uses normal customer properties and learner link, then updates without duplicate',async()=>{const f=fixture();const first=await publishPlan(f.request,profile,[{day:1,title:'Bài 1',link:'7342f32a-7183-4d39-a9ba-564839dd247e'}],{creatorEmail:'qa@example.test'});assert.equal(first.sdt,'');assert.equal(first.video_date,null);assert.equal(first.trang_thai,0);assert.equal(first.trang_thai_gan,'1');assert.equal(first.is_consultation,true);assert.ok(first.created_at);assert.ok(first.link.startsWith('https://phacdo.com/client/C-QA?t='));assert.equal(first.raw_backup.creator_email,'qa@example.test');assert.equal(f.tasks.length,1);const updated=await publishPlan(f.request,{...profile,customer_name:'QA updated'},[{day:2,title:'Bài 2'}],{expectedUpdatedAt:first.updated_at});assert.equal(updated.token,first.token);assert.equal(updated.created_at,first.created_at);assert.equal(f.tasks.length,1);assert.equal(f.tasks[0].day,2);assert.equal(f.customer.customer_name,'QA updated');});
test('stale editor cannot overwrite a normal dashboard edit',async()=>{const f=fixture();await publishPlan(f.request,profile,[]);await assert.rejects(publishPlan(f.request,profile,[],{expectedUpdatedAt:'old'}),/Mở lại/);});
test('failed task write restores existing profile and retains old tasks',async()=>{const f=fixture();const first=await publishPlan(f.request,profile,[{day:1,title:'Old'}]);f.fail();await assert.rejects(publishPlan(f.request,{...profile,customer_name:'Wrong'},[{day:2,title:'New'}],{expectedUpdatedAt:first.updated_at}),/task write failed/);assert.equal(f.customer.customer_name,'QA');assert.equal(f.tasks.length,1);assert.equal(f.tasks[0].title,'Old');});
test('failed first save does not leave an empty new learner',async()=>{const f=fixture();f.fail();await assert.rejects(publishPlan(f.request,profile,[{day:1,title:'New'}]),/task write failed/);assert.equal(f.customer,null);});
