import test from 'node:test';import assert from 'node:assert/strict';import {mkdirSync,mkdtempSync} from 'node:fs';import {resolve,join} from 'node:path';import ExcelJS from 'exceljs';
mkdirSync('test-data',{recursive:true});process.env.DATA_DIR=mkdtempSync(join(resolve('test-data'),'quick-replies-'));
const {put,get,all}=await import('../server/store.mjs');const {quickReplyRoute:route}=await import('../server/quick-replies.mjs');const {runTemplate}=await import('../server/taophacdo.mjs');const user={id:'owner',role:'owner'},base='/api/quick-replies/';
test('topics, multi-content replies and Excel roundtrip preserve media, cards and ordering',async()=>{
 put('connections',{id:'demo',name:'QA',mode:'demo',provider:'zalo_personal',status:'connected'});put('customers',{id:'p',name:'An'});put('conversations',{id:'c',customerId:'p',connectionId:'demo',kind:'message',status:'open'});put('conversations',{id:'friend',customerId:'p',connectionId:'demo',externalUserId:'u',threadType:0,isFriend:true});put('assets',{id:'a',type:'file',url:'/uploads/asset_qa.pdf',name:'Tài liệu',active:true,scopes:['chat','template']});
 const topic=await route(base+'topics','POST',{name:'Học phí',color:'#1890ff',sortOrder:2},user);
 const t=await route(base+'templates','POST',{name:'Khóa học',shortcut:'*',topicId:topic.id,sortOrder:3,blocks:[{text:'Chào {{name}}',assetIds:['a']},{text:'Danh bạ',contactIds:['friend']}]},user);assert.equal(t.blocks.length,2);assert.equal(t.topicId,topic.id);
 await assert.rejects(route(base+'templates','POST',{name:'Trùng',shortcut:'*',blocks:[{text:'x'}]},user),/đã tồn tại/);await assert.rejects(route(base+'topics/'+topic.id,'DELETE',{version:topic.version},user),/đang được dùng/);await assert.rejects(route(base+'templates/'+t.id,'PATCH',{...t,version:999},user),/đã thay đổi/);
 const exported=await route(base+'excel/export','POST',{},user),book=new ExcelJS.Workbook();await book.xlsx.load(Buffer.from(exported.file,'base64'));const sheet=book.getWorksheet('Tin nhan nhanh');assert.equal(sheet.getCell('I3').value,'friend');assert.equal(sheet.getCell('H2').value,'a');for(let i=2;i<=3;i++){sheet.getCell(i,2).value='Bản nhập';sheet.getCell(i,3).value='(';}const file=Buffer.from(await book.xlsx.writeBuffer()).toString('base64');const preview=await route(base+'excel/preview','POST',{file},user);assert.equal(preview.ready,1);assert.equal(preview.errors,0);assert.equal((await route(base+'excel/import','POST',{file},user)).imported,1);const copy=all('templates').find(t=>t.name==='Bản nhập');assert.deepEqual(copy.blocks,t.blocks);assert.equal(copy.topicId,topic.id);assert.equal((await route(base+'excel/preview','POST',{file},user)).duplicates,1);
 sheet.getCell('G2').value={formula:'1+1',result:2};const bad=Buffer.from(await book.xlsx.writeBuffer()).toString('base64');await assert.rejects(route(base+'excel/import','POST',{file:bad},user),/dòng lỗi/);assert.equal(all('templates').length,2);
 // All card/channel prerequisites are checked before sending any part.
 await assert.rejects(runTemplate(user,'c',{templateId:t.id}),/Zalo API/);assert.equal(all('messages').length,0);
 const seq=await route(base+'templates','POST',{name:'Chuỗi tệp',shortcut:'+',blocks:[{text:'Chào {{name}}',assetIds:['a']},{text:'Tiếp theo'}]},user);const sent=await runTemplate(user,'c',{templateId:seq.id});assert.equal(sent.status,'done');assert.equal(get('messages',sent.messageIds[0]).text,'Chào An');assert.equal(get('messages',sent.messageIds[0]).attachments[0].assetId,'a');assert.equal(get('messages',sent.messageIds[1]).attachments.length,0);await assert.rejects(runTemplate(user,'c',{runId:sent.id}));
 await assert.rejects(route(base+'templates','POST',{name:'Sai',shortcut:'123',blocks:[{text:'x'}]},user),/chỉ gồm số/);await assert.rejects(route(base+'templates','POST',{name:'Sai',blocks:[{assetIds:['missing']}]},user),/Tệp/);await assert.rejects(route(base+'templates','POST',{name:'Sai',blocks:[{}]},user),/văn bản/);await assert.rejects(route(base+'topics','POST',{name:'Quyền',color:'#1890ff'}, {id:'viewer',role:'viewer'}),/quyền/i);
});
test('export supports legacy templates without a topic and preserves their shared attachments',async()=>{put('templates',{name:'Mẫu cũ',text:'Chào bạn',assetIds:['a'],blocks:[{text:'Chào bạn'},{text:'Tiếp theo'}]});const out=await route(base+'excel/export','POST',{},user),b=new ExcelJS.Workbook();await b.xlsx.load(Buffer.from(out.file,'base64'));const s=b.getWorksheet('Tin nhan nhanh'),rows=[];s.eachRow((r,i)=>{if(i>1&&r.getCell(2).value==='Mẫu cũ')rows.push(r);});assert.equal(rows.length,2);assert.equal(rows[0].getCell(8).value,'a');assert.equal(rows[1].getCell(8).value,'');});
test('a replayed request after a lost response cannot send the same sequence twice',async()=>{const t=await route(base+'templates','POST',{name:'Chống trùng',shortcut:'chongtrung',blocks:[{text:'Lần một'},{text:'Lần hai'}]},user);const before=all('messages').length,first=await runTemplate(user,'c',{templateId:t.id,requestId:'unique-reply'}),second=await runTemplate(user,'c',{templateId:t.id,requestId:'unique-reply'});assert.equal(first.id,second.id);assert.equal(second.status,'done');assert.equal(all('messages').length,before+2);await assert.rejects(runTemplate(user,'c',{templateId:'other',requestId:'unique-reply'}),/mẫu khác/);});
