import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
process.env.DATA_DIR=mkdtempSync(join(tmpdir(),'vtp-test-'));process.env.PLAN_REMOTE_CATALOG='0';
const {put,get,all,secret,db}=await import('../server/store.mjs');
const {createOrder,orderAction,shipmentAction}=await import('../server/domain.mjs');
const {shippingRoute,dispatchShipment,receiveVtpWebhook,shippingState}=await import('../server/shipping.mjs');
const {vtpRequest,providerDate,mappedStatus}=await import('../server/viettelpost.mjs');
const owner={id:'owner-vtp',role:'owner',name:'Owner'};
put('customers',{id:'vtp-customer',name:'Khách QA',phone:'0901234567',address:'12 Nguyễn Trãi, phường Bến Thành, TP Hồ Chí Minh',createdBy:owner.id});
put('products',{id:'vtp-product',name:'Sản phẩm QA',sku:'VTPQA',price:100000,cost:50000,stock:100,reserved:0,weight:250,productType:'physical'});
let account;
const request=async(env,path,options)=>{if(path==='/v2/user/listInventory')return [{groupaddressId:42,name:'Kho QA',phone:'0901234568',address:'19 Duy Tân, Hà Nội'}];throw Error('Unexpected '+path);};
const newOrder=()=>createOrder(owner,{customerId:'vtp-customer',phone:'0901234567',address:'12 Nguyễn Trãi, phường Bến Thành, TP Hồ Chí Minh',items:[{productId:'vtp-product',quantity:2}]});
const body=o=>({accountId:account.id,version:o.version,weight:500,length:20,width:15,height:10,service:'VCN',payment:3,cod:o.total,declaredValue:o.subtotal});
const event=(s,code,date='09/10/2026 15:00:00')=>({TOKEN:secret('carrier:'+account.id).webhookToken,DATA:{ORDER_NUMBER:s.tracking,ORDER_REFERENCE:s.reference,ORDER_STATUS:code,ORDER_STATUSDATE:date,STATUS_NAME:'Trạng thái '+code,MONEY_TOTAL:30000,EMPLOYEE_NAME:'Nhân viên giao QA'}});

test('NLP price adapter accepts documented RESULT response while creation remains strict',async()=>{
 const rows=[{MA_DV_CHINH:'SCN',TEN_DICHVU:'Chuyển phát nhanh',GIA_CUOC:41440}];
 for(const value of [{SENDER_ADDRESS:{},RECEIVER_ADDRESS:{},RESULT:rows},{status:200,data:{RESULT:rows}},{status:200,data:rows}])assert.deepEqual(await vtpRequest('production','/v2/order/getPriceAllNlp',{fetcher:async()=>new Response(JSON.stringify(value))}),rows);
 await assert.rejects(vtpRequest('production','/v2/order/createOrderNlp',{fetcher:async()=>new Response(JSON.stringify({RESULT:rows}))}),e=>e.unknown===true);
 await assert.rejects(vtpRequest('production','/v2/order/getPriceAllNlp',{fetcher:async()=>new Response(JSON.stringify({status:400,error:true,message:'Rejected',RESULT:rows}))}),/Rejected/);
 await assert.rejects(vtpRequest('production','/v2/order/getPriceAllNlp',{fetcher:async()=>new Response(JSON.stringify({RESULT:[{MA_DV_CHINH:'SCN',GIA_CUOC:-1}]}))}),/thiếu trạng thái/);
});
test('course-only quick order completion never dispatches to carrier even when account was previously selected',async()=>{
 const {completeOrderShipping}=await import('../public/shipping-ui.js');const o={id:'course-only-qa',requiresShipping:false,status:'draft'};
 assert.equal(await completeOrderShipping({elements:{vtpAccount:{value:'selected-account'}}},o,{api:()=>assert.fail('must not dispatch')}),o);
});

test('historical import verifies identity and account warehouse, is idempotent and does not affect stock or payments',async()=>{
 const a=await shippingRoute('/api/shipping/accounts','POST',{token:'history-qa',name:'History QA'},owner,request),before=JSON.stringify([all('orders'),all('products'),all('payments')]);
 const detail={ORDER_NUMBER:'PKE-QA',GROUPADDRESS_ID:42,RECEIVER_FULLNAME:'Khách cũ QA',RECEIVER_PHONE:'0901234567',PRODUCT_NAME:'Hàng cũ',MONEY_COLLECTION:330000,ORDER_STATUS:400,ORDER_SYSTEMDATE:'08/10/2026 16:05:19',ORDER_STATUSDATE:'09/10/2026 03:04:11'};
 const mock=async(env,path,options)=>{assert.equal(path,'/v2/order/detail-v2');assert.equal(options.method,'GET');assert.deepEqual(options.query,{o:'PKE-QA'});return detail;};
 const route='/api/shipping/accounts/'+a.id+'/sync-history';let r=await shippingRoute(route,'POST',{tracking:'PKE-QA PKE-QA'},owner,mock);assert.equal(r.created,1);assert.equal(r.attempted,1);
 r=await shippingRoute(route,'POST',{tracking:'PKE-QA'},owner,mock);assert.equal(r.updated,1);assert.equal(all('carrier_orders').filter(o=>o.accountId===a.id).length,1);assert.equal(JSON.stringify([all('orders'),all('products'),all('payments')]),before);
 await assert.rejects(shippingRoute(route,'POST',{}, {id:'support',role:'support'},mock),/chủ hệ thống/);
 r=await shippingRoute(route,'POST',{tracking:'bad-qa'},owner,async()=>({...detail,ORDER_NUMBER:'different'}));assert.equal(r.failed.length,1);assert.equal(r.created,0);
 r=await shippingRoute(route,'POST',{tracking:'other-warehouse'},owner,async()=>({...detail,ORDER_NUMBER:'other-warehouse',GROUPADDRESS_ID:100}));assert.equal(r.failed.length,1);assert.equal(all('carrier_orders').filter(o=>o.accountId===a.id).length,1);
});
test('verified historical record replays callback and never treats unknown callback sample as a complete order',async()=>{
 const a=await shippingRoute('/api/shipping/accounts','POST',{token:'callback-history-qa',name:'Callback History QA'},owner,request),token=secret('carrier:'+a.id).webhookToken;
 const p={TOKEN:token,DATA:{ORDER_NUMBER:'old-callback',ORDER_STATUS:501,ORDER_STATUSDATE:'09/10/2026 18:00:00',STATUS_NAME:'Phát thành công'}};receiveVtpWebhook(a.id,{},p);
 let r=await shippingRoute('/api/shipping/accounts/'+a.id+'/sync-history','POST',{},owner,async()=>({ORDER_NUMBER:'old-callback',GROUPADDRESS_ID:42,RECEIVER_FULLNAME:'Khách cũ',ORDER_STATUS:400,ORDER_STATUSDATE:'09/10/2026 03:00:00'}));assert.equal(r.created,1);
 const o=all('carrier_orders').find(o=>o.accountId===a.id);assert.equal(o.status,'delivered');assert.equal(o.history.length,1);receiveVtpWebhook(a.id,{},p);assert.equal(get('carrier_orders',o.id).history.length,1);
 receiveVtpWebhook(a.id,{}, {...p,DATA:{...p.DATA,ORDER_STATUS:400,ORDER_STATUSDATE:'09/10/2026 02:00:00'}});assert.equal(get('carrier_orders',o.id).status,'delivered');
 const b=await shippingRoute('/api/shipping/accounts','POST',{token:'empty-history-qa',name:'Empty History QA'},owner,request);r=await shippingRoute('/api/shipping/accounts/'+b.id+'/sync-history','POST',{},owner,async()=>{throw Error('should not call');});assert.equal(r.attempted,0);assert.equal(r.created,0);
});
test('detail query is encoded and rejects unsupported parameters before network',async()=>{
 await vtpRequest('production','/v2/order/detail-v2',{method:'GET',query:{o:'PKE1542069448'},fetcher:async(url,opts)=>{assert.equal(url,'https://partner.viettelpost.vn/v2/order/detail-v2?o=PKE1542069448');assert.equal(opts.method,'GET');return new Response(JSON.stringify({status:200,data:{}}));}});
 await assert.rejects(vtpRequest('production','/v2/order/detail-v2',{query:{o:'a&b'},fetcher:()=>assert.fail('must not fetch')}),/Tham số/);
 await assert.rejects(vtpRequest('production','/v2/user/Login',{query:{o:'test'},fetcher:()=>assert.fail('must not fetch')}),/Tham số/);
});

test('website token is exchanged through LoginVTP before reading inventory, ignores unrelated credentials',async()=>{const calls=[];const a=await shippingRoute('/api/shipping/accounts','POST',{authMode:'website-token',name:'Website Token QA',token:'  opaque-website-key  ',ownerUsername:'autofill-shop',ownerPassword:'autofill-password'},owner,async(env,path,options)=>{calls.push(path);if(path.endsWith('/LoginVTP')){assert.deepEqual(options.body,{token:'opaque-website-key'});assert.equal(options.token,undefined);return {token:'exchanged-api-token'};}assert.equal(path,'/v2/user/listInventory');assert.equal(options.token,'exchanged-api-token');return [];});assert.deepEqual(calls,['/v2/user/LoginVTP','/v2/user/listInventory']);assert.equal(secret('carrier:'+a.id).token,'exchanged-api-token');assert.ok(!JSON.stringify(secret('carrier:'+a.id)).includes('opaque-website-key'));});
test('website exchange failures identify the stage and preserve saved credentials',async()=>{const a=await shippingRoute('/api/shipping/accounts','POST',{name:'Website failed QA',token:'existing-token'},owner,async()=>[]);await assert.rejects(shippingRoute('/api/shipping/accounts','POST',{id:a.id,version:a.version,name:a.name,authMode:'website-token',token:'secret-website-key'},owner,async()=>{throw Error('Rejected secret-website-key');}),e=>e.message.includes('LoginVTP')&&!e.message.includes('secret-website-key'));assert.equal(secret('carrier:'+a.id).token,'existing-token');assert.equal(get('shipping_accounts',a.id).version,a.version);await assert.rejects(shippingRoute('/api/shipping/accounts','POST',{name:'Empty website QA',authMode:'website-token',token:'key'},owner,async()=>({})),/chưa trả token từ LoginVTP/);});
test('adapter redacts website token in LoginVTP response errors',async()=>{await assert.rejects(vtpRequest('production','/v2/user/LoginVTP',{body:{token:'private-website-key'},fetcher:async()=>new Response(JSON.stringify({status:400,error:true,message:'Rejected private-website-key'}))}),e=>!e.message.includes('private-website-key'));});

test('supplied Partner token exchanges shop credentials even without Partner login',async()=>{const calls=[];const a=await shippingRoute('/api/shipping/accounts','POST',{name:'Supplied Partner QA',token:'  partner-token  ',ownerUsername:'shop-qa',ownerPassword:'shop-password'},owner,async(env,path,options)=>{calls.push(path);if(path.endsWith('/ownerconnect')){assert.equal(options.token,'partner-token');assert.deepEqual(options.body,{USERNAME:'shop-qa',PASSWORD:'shop-password'});return {token:'shop-long-token'};}assert.equal(path,'/v2/user/listInventory');assert.equal(options.token,'shop-long-token');return [];});assert.deepEqual(calls,['/v2/user/ownerconnect','/v2/user/listInventory']);assert.equal(secret('carrier:'+a.id).token,'shop-long-token');assert.ok(!JSON.stringify(secret('carrier:'+a.id)).includes('shop-password'));});
test('rejected shop exchange and missing token preserve an existing connection',async()=>{const a=await shippingRoute('/api/shipping/accounts','POST',{name:'Existing Auth QA',token:'original-token'},owner,async()=>[]);await assert.rejects(shippingRoute('/api/shipping/accounts','POST',{id:a.id,version:a.version,name:a.name,token:'invalid-partner',ownerUsername:'shop',ownerPassword:'password'},owner,async()=>{throw Error('Shop rejected');}),/Shop rejected/);assert.equal(secret('carrier:'+a.id).token,'original-token');assert.equal(get('shipping_accounts',a.id).version,a.version);await assert.rejects(shippingRoute('/api/shipping/accounts','POST',{name:'Missing token QA',ownerUsername:'shop',ownerPassword:'password'},owner,async()=>{throw Error('must not call');}),/token Partner/);await assert.rejects(shippingRoute('/api/shipping/accounts','POST',{name:'Empty exchange QA',token:'partner',ownerUsername:'shop',ownerPassword:'password'},owner,async()=>({})),/chưa trả token shop/);});
test('invalidated carrier session error gives actionable guidance and redacts secrets',async()=>{await assert.rejects(vtpRequest('production','/v2/user/listInventory',{token:'private-session',method:'GET',fetcher:async()=>new Response(JSON.stringify({status:400,error:true,message:'Account have logged in on another machine! private-session'}))}),error=>error.message.includes('LoginVTP')&&error.message.includes('token Partner')&&!error.message.includes('private-session'));});

test('sync diagnostics distinguish authenticated unmatched callbacks and never expose credentials',async()=>{const a=await shippingRoute('/api/shipping/accounts','POST',{name:'Diagnostic QA',token:'diagnostic-secret'},owner,request);await assert.rejects(shippingRoute('/api/shipping/accounts/'+a.id+'/diagnostics','GET',{}, {id:'support',role:'support'}),/chủ hệ thống/);let d=await shippingRoute('/api/shipping/accounts/'+a.id+'/diagnostics','GET',{},owner);assert.equal(d.connected,true);assert.equal(d.senderReady,false);assert.equal(d.events.total,0);assert.equal(d.historicalImportAvailable,true);receiveVtpWebhook(a.id,{}, {TOKEN:secret('carrier:'+a.id).webhookToken,DATA:{ORDER_NUMBER:'unmatched-qa',ORDER_STATUS:200,ORDER_STATUSDATE:'09/10/2026 15:00:00'}});d=await shippingRoute('/api/shipping/accounts/'+a.id+'/diagnostics','GET',{},owner);assert.equal(d.events.total,1);assert.equal(d.events.unmatched,1);assert.ok(d.events.lastReceivedAt);assert.ok(!JSON.stringify(d).includes('diagnostic-secret'));});
test('account connections are owner-only, validate remotely and encrypt credentials',async()=>{await assert.rejects(shippingRoute('/api/shipping/accounts','POST',{name:'Không được',token:'private'}, {id:'support',role:'support'},request),/chủ hệ thống/);account=await shippingRoute('/api/shipping/accounts','POST',{name:'VTP QA',token:'private-vtp-token',environment:'sandbox',sender:{name:'Kho QA',phone:'0901234568',address:'19 Duy Tân, Cầu Giấy, Hà Nội'}},owner,request);assert.equal(secret('carrier:'+account.id).token,'private-vtp-token');assert.ok(!JSON.stringify(shippingState(owner)).includes('private-vtp-token'));assert.ok(!db.prepare('SELECT value FROM secrets WHERE id=?').get('carrier:'+account.id).value.includes('private-vtp-token'));});
test('creates a real adapter request, stores reference, fees and prevents duplicate dispatch',async()=>{const o=newOrder();let calls=0;const s=await dispatchShipment(owner,o.id,body(o),async(env,path,{token,body:p})=>{calls++;assert.equal(env,'sandbox');assert.equal(path,'/v2/order/createOrderNlp');assert.equal(token,'private-vtp-token');assert.equal(p.CHECK_UNIQUE,true);assert.equal(p.ORDER_NUMBER,o.code);assert.equal(p.PRODUCT_WEIGHT,500);assert.equal(p.MONEY_COLLECTION,200000);return {ORDER_NUMBER:'VTP-QA-'+o.id,MONEY_TOTAL:30000};});assert.equal(s.status,'pickup_pending');assert.equal(s.fee,30000);assert.equal(get('orders',o.id).status,'confirmed');await assert.rejects(dispatchShipment(owner,o.id,{...body(o),version:get('orders',o.id).version},async()=>{calls++;}),/đã có vận đơn/);assert.equal(calls,1);});
test('unknown network result persists and cannot be automatically retried',async()=>{const o=newOrder();await assert.rejects(dispatchShipment(owner,o.id,body(o),async()=>{throw Object.assign(Error('Mất kết nối'),{unknown:true});}),/Mất kết nối/);assert.equal(get('orders',o.id).shippingState,'unknown');assert.equal(all('shipments').find(s=>s.orderId===o.id).status,'unknown');await assert.rejects(dispatchShipment(owner,o.id,{...body(o),version:get('orders',o.id).version},async()=>{throw Error('Must not call');}),/đã có vận đơn/);});
test('definite rejection permits an explicit retry using the same reference',async()=>{const o=newOrder();await assert.rejects(dispatchShipment(owner,o.id,body(o),async()=>{throw Error('Địa chỉ chưa đúng');}),/Địa chỉ/);assert.equal(get('orders',o.id).shippingState,'failed');const s=await dispatchShipment(owner,o.id,{...body(o),version:get('orders',o.id).version},async()=>({ORDER_NUMBER:'retry-'+o.id}));assert.equal(s.status,'pickup_pending');assert.equal(db.prepare('SELECT COUNT(*) AS n FROM shipping_requests WHERE order_id=?').get(o.id).n,1);});
test('validates address, available COD, revision, and staff access before calling provider',async()=>{const o=newOrder(),noCall=async()=>{throw Error('Should never call');};await assert.rejects(dispatchShipment(owner,o.id,{...body(o),cod:o.total+1},noCall),/Tiền thu hộ/);await assert.rejects(dispatchShipment(owner,o.id,{...body(o),version:999},noCall),/đã thay đổi/);await assert.rejects(dispatchShipment({id:'outsider',role:'support'},o.id,body(o),noCall),/phân công/);assert.equal(get('orders',o.id).status,'draft');});
test('webhooks authenticate, deduplicate, preserve order chronology and dispatch inventory once',async()=>{const o=newOrder(),s=await dispatchShipment(owner,o.id,body(o),async()=>({ORDER_NUMBER:'events-'+o.id}));const before=get('products','vtp-product').stock;assert.throws(()=>receiveVtpWebhook(account.id,{}, {...event(s,200),TOKEN:'wrong'}),/xác thực/);const p=event(s,200);receiveVtpWebhook(account.id,{},p);receiveVtpWebhook(account.id,{},p);assert.equal(get('products','vtp-product').stock,before-2);receiveVtpWebhook(account.id,{},event(s,501,'09/10/2026 16:00:00'));assert.equal(get('orders',o.id).status,'delivered');assert.equal(get('orders',o.id).paid,0);assert.equal(all('payments').filter(p=>p.orderId===o.id).length,0);receiveVtpWebhook(account.id,{},event(s,300,'09/10/2026 14:00:00'));assert.equal(get('shipments',s.id).status,'delivered');assert.equal(get('products','vtp-product').stock,before-2);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM shipping_events WHERE tracking=?').get(s.tracking).n,3);assert.throws(()=>shipmentAction(owner,s.id,{status:'returned'}),/nhận từ hãng/);});
test('carrier return waits for staff inspection and does not automatically restock',async()=>{const o=newOrder(),s=await dispatchShipment(owner,o.id,body(o),async()=>({ORDER_NUMBER:'return-'+o.id}));receiveVtpWebhook(account.id,{},event(s,200));const before=get('products','vtp-product').stock;receiveVtpWebhook(account.id,{},event(s,504,'09/10/2026 17:00:00'));assert.equal(get('orders',o.id).status,'return_pending_check');assert.equal(get('products','vtp-product').stock,before);orderAction(owner,o.id,{action:'return',items:[{productId:'vtp-product',quantity:2,restock:true}],reason:'Đã kiểm hàng'});assert.equal(get('products','vtp-product').stock,before+2);});
test('cancel webhook releases reservation once, pending cancellation request does not',async()=>{const o=newOrder(),s=await dispatchShipment(owner,o.id,body(o),async()=>({ORDER_NUMBER:'cancel-'+o.id}));const before=get('products','vtp-product').reserved;await shippingRoute('/api/shipping/shipments/'+s.id+'/cancel','POST',{note:'Khách hủy'},owner,async(env,path,{body:p})=>{assert.equal(path,'/v2/order/UpdateOrder');assert.equal(p.TYPE,4);return {};});assert.equal(get('products','vtp-product').reserved,before);const p=event(s,201);receiveVtpWebhook(account.id,{},p);receiveVtpWebhook(account.id,{},p);assert.equal(get('products','vtp-product').reserved,before-2);assert.equal(get('orders',o.id).status,'cancelled');});
test('pending early callback is replayed after create response supplies tracking',async()=>{const o=newOrder(),s=await dispatchShipment(owner,o.id,body(o),async()=>{receiveVtpWebhook(account.id,{},event({tracking:'early-'+o.id,reference:o.code},200));return {ORDER_NUMBER:'early-'+o.id};});assert.equal(s.status,'in_transit');assert.equal(get('orders',o.id).status,'fulfilling');});
test('HTTP adapter rejects cross-host endpoints, business errors and ambiguous gateway results',async()=>{await assert.rejects(vtpRequest('evil','/v2/user/Login'),/không hợp lệ/);await assert.rejects(vtpRequest('production','/v2/user/Login',{fetcher:async()=>new Response(JSON.stringify({status:400,error:true,message:'Bad login'}),{status:200})}),/Bad login/);await assert.rejects(vtpRequest('production','/v2/user/Login',{fetcher:async()=>new Response('not json',{status:502})}),e=>e.unknown===true);assert.equal(providerDate('09/10/2026 15:00:00'),'2026-10-09T08:00:00.000Z');});
test('late authenticated webhook recovers an ambiguous request using the scoped reference',async()=>{const o=newOrder();await assert.rejects(dispatchShipment(owner,o.id,body(o),async()=>{throw Object.assign(Error('Timeout'),{unknown:true});}));const s=all('shipments').find(s=>s.orderId===o.id);receiveVtpWebhook(account.id,{},event({...s,tracking:'recovered-'+o.id},105));assert.equal(get('shipments',s.id).tracking,'recovered-'+o.id);assert.equal(get('shipments',s.id).status,'in_transit');assert.equal(db.prepare('SELECT state FROM shipping_requests WHERE id=?').get(s.requestId).state,'accepted');});
test('account login exchanges a partner token for the owner token and never stores passwords',async()=>{let step=0;const a=await shippingRoute('/api/shipping/accounts','POST',{name:'Shop token QA',username:'partner-qa',password:'secret-partner',ownerUsername:'shop-qa',ownerPassword:'secret-shop'},owner,async(env,path,options)=>{step++;if(path.endsWith('/Login'))return {token:'short-token'};if(path.endsWith('/ownerconnect')){assert.equal(options.token,'short-token');assert.equal(options.body.USERNAME,'shop-qa');return {token:'long-token'};}return [];});assert.equal(step,3);assert.equal(secret('carrier:'+a.id).token,'long-token');assert.ok(!JSON.stringify(secret('carrier:'+a.id)).includes('secret-shop'));});
test('official COD types and return status mapping prevent unintended collection',async()=>{const o=newOrder();await assert.rejects(dispatchShipment(owner,o.id,{...body(o),payment:1},async()=>{throw Error('must not send');}),/không thu hộ tiền hàng/);assert.equal(mappedStatus(502),'returning');assert.equal(mappedStatus(515),'returning');assert.equal(mappedStatus(550),'in_transit');assert.equal(mappedStatus(107),null);const s=await dispatchShipment(owner,o.id,body(o),async()=>({ORDER_NUMBER:'print-'+o.id}));const r=await shippingRoute('/api/shipping/shipments/'+s.id+'/label','POST',{},owner,async(env,path,options)=>{assert.equal(path,'/v2/order/printing-code');assert.deepEqual(options.body.ORDER_ARRAY,[s.tracking]);assert.equal(options.fullResponse,true);return {message:'abcdefghijklmnopqrstuvwxyz123456='};});assert.equal(new URL(r.url).hostname,'dev-release-print.viettelpost.vn');});
