import {get,put,secret} from './store.mjs';
import {requestProvider} from './ai-provider.mjs';
const inflight=new Map();
export const poolIds=bot=>[...new Set(bot?.aiConnectionIds?.length?bot.aiConnectionIds:[bot?.aiConnectionId].filter(Boolean))];
export const configuredConnections=bot=>poolIds(bot).map(id=>get('ai_connections',id)).filter(c=>c?.enabled&&secret('bot-ai:'+c.id).token);
export function connectionHealth(c){const h=get('settings','ai-health:'+c.id)||{};return {...h,id:c.id,inFlight:inflight.get(c.id)||0,state:!c.enabled?'disabled':!secret('bot-ai:'+c.id).token?'missing_key':h.configVersion!==c.version?'untested':h.cooldownUntil&&Date.parse(h.cooldownUntil)>Date.now()?'cooldown':h.lastError?'retry_ready':h.lastSuccessAt?'healthy':'untested',errorRate:h.attempts?Math.round(h.errors/h.attempts*1000)/10:0};}
export async function trackedCall(c,prompt,provider=requestProvider){const started=Date.now();inflight.set(c.id,(inflight.get(c.id)||0)+1);try{const result=await provider(c,prompt);record(c,null,started);return result;}catch(err){record(c,err,started);throw err;}finally{const n=(inflight.get(c.id)||1)-1;if(n)inflight.set(c.id,n);else inflight.delete(c.id);}}
function record(c,err,started){if(get('ai_connections',c.id)?.version!==c.version)return;const old=get('settings','ai-health:'+c.id)||{},status=err?.status||0;const duration=err?(status===429?60000:[401,403,404].includes(status)?300000:15000):0;put('settings',{...old,id:'ai-health:'+c.id,configVersion:c.version,attempts:(old.attempts||0)+1,errors:(old.errors||0)+(err?1:0),quotaErrors:(old.quotaErrors||0)+(status===429?1:0),consecutiveErrors:err?(old.consecutiveErrors||0)+1:0,lastAttemptAt:new Date().toISOString(),lastSuccessAt:err?old.lastSuccessAt:new Date().toISOString(),lastError:err?String(err.message).replaceAll(secret('bot-ai:'+c.id).token||'__no_key__','[API key đã ẩn]').slice(0,1200):'',lastStatus:status,lastLatencyMs:Date.now()-started,cooldownUntil:duration?new Date(Date.now()+duration).toISOString():null});}
export async function pooledCall(bot,prompt,provider=requestProvider){const candidates=configuredConnections(bot).filter(c=>{const h=connectionHealth(c);return h.state!=='cooldown';});if(!candidates.length){const configured=configuredConnections(bot),health=configured.map(connectionHealth),retryable=health.some(h=>[408,429,502,503,504].includes(h.lastStatus));throw Object.assign(Error(configured.length?'Các kết nối AI đang tạm nghỉ sau lỗi; hệ thống sẽ thử lại sau.':'Tất cả kết nối AI đang tắt hoặc thiếu khóa.'),{status:configured.length?503:400,retryable,retryAt:health.map(h=>h.cooldownUntil).filter(Boolean).sort()[0]});}const cursor=get('settings','ai-pool:'+bot.id)?.cursor||0,start=cursor%candidates.length;put('settings',{id:'ai-pool:'+bot.id,cursor:cursor+1});const attempts=[];for(let i=0;i<candidates.length;i++){const c=candidates[(start+i)%candidates.length];try{const text=await trackedCall(c,prompt,provider);if(get('ai_connections',c.id)?.version!==c.version)throw Error('Cấu hình kết nối đã thay đổi trong lúc gọi AI.');attempts.push({connectionId:c.id,status:'success'});return {text,connectionId:c.id,attempts};}catch(err){attempts.push({connectionId:c.id,status:'error',code:err.status||0});}}throw Object.assign(Error('Không có kết nối AI phản hồi thành công. Đã thử '+attempts.length+' kết nối; xem tình trạng từng kết nối.'),{attempts,status:503,retryable:attempts.some(a=>[408,429,502,503,504].includes(a.code)),retryAt:configuredConnections(bot).map(c=>connectionHealth(c).cooldownUntil).filter(Boolean).sort()[0]});}
