import {all,get,put,transaction,audit,now} from './store.mjs';
import {permission,fail} from './domain.mjs';
import {assertChannel} from './taophacdo.mjs';

export function deleteChats(user,input){permission(user,'inbox');if(input.confirm!==true)fail('Xác nhận xóa hội thoại.');if(!Array.isArray(input.items)||!input.items.length||input.items.length>100)fail('Chọn 1–100 hội thoại.');const ids=new Set();return transaction(()=>{
 const rows=input.items.map(item=>{if(ids.has(item.id))fail('Hội thoại bị lặp.');ids.add(item.id);const c=get('conversations',item.id);if(!c||c.deletedAt||c.kind==='comment')fail('Không tìm thấy hội thoại chat.',404);assertChannel(user,c.connectionId);if(item.version!==c.version)fail('Hội thoại có tin mới hoặc đã thay đổi. Tải lại trước khi xóa.',409);if(c.sending||all('messages').some(m=>m.conversationId===c.id&&m.status==='sending')||all('chatbot_jobs').some(j=>j.conversationId===c.id&&j.status==='dispatching'))fail('Hội thoại đang gửi tin nhắn. Chờ gửi xong trước khi xóa.',409);return c;});
 const at=now();for(const c of rows){put('conversations',{...c,deletedAt:at,deletedBy:user.id,clearedBefore:at,unread:false,waitingSince:null,status:'resolved',archived:true},c.version);for(const m of all('messages').filter(m=>m.conversationId===c.id&&!m.deletedAt))put('messages',{...m,deletedAt:at});for(const j of all('chatbot_jobs').filter(j=>j.conversationId===c.id&&['waiting','running'].includes(j.status)))put('chatbot_jobs',{...j,status:'cancelled',cancelReason:'conversation_deleted'});for(const kind of ['staff_handoffs','chat_reminders'])for(const task of all(kind).filter(t=>t.conversationId===c.id&&!['resolved','done','cancelled'].includes(t.status)))put(kind,{...task,status:kind==='staff_handoffs'?'resolved':'cancelled',resolvedAt:at,resolvedBy:user.id,resolution:'conversation_deleted'});audit(user.id,'conversation_deleted',c.id,{messageHistoryHidden:true});}return {deletedIds:rows.map(c=>c.id)};
 });}
export function filterDeletedChats(state){state.conversations=state.conversations.filter(c=>!c.deletedAt);const rows=new Map(state.conversations.map(c=>[c.id,c]));state.messages=state.messages.filter(m=>!m.deletedAt&&rows.has(m.conversationId)&&(!rows.get(m.conversationId).clearedBefore||m.createdAt>rows.get(m.conversationId).clearedBefore));return state;}
