import {checkConsultation,finishConsultation,progressState} from './consultation-review.mjs';
import {latestContact} from '../public/chat-contact-data.js';
import {syncCommonGroups} from './zalo.mjs';
import {commonGroups,relationshipsRoute} from './chat-relationships.mjs';
import {listPlanSources,getPlanSource} from './plan-sources.mjs';
import {studyPlanStatus} from './plan-access.mjs';
import {all,get,put,transaction,audit,now} from './store.mjs';
import {permission,fail,number,createOrder} from './domain.mjs';
import {assertCustomer,assertChannel,planFor,phonesIn,syncPaymentOrder} from './taophacdo.mjs';
import {readLearner,writeLearner,readLearnerActivity,readPlanCatalog,readPlanProfile} from './supabase.mjs';
import {learnerStages,progressFor,stageRank,deletedLearner} from '../public/learner-progress.js';

const date=value=>{const parsed=Date.parse(value+'T00:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(value||'')||!Number.isFinite(parsed)||new Date(parsed).toISOString().slice(0,10)!==value)fail('Ngày không hợp lệ.');return value;};
const isCourse=p=>p.productType==='course'||p.id_sp==='SP1768731546380'||/khóa học|khoá học|khoa hoc/i.test(p.ten_sp||p.name||'');
const addDays=(base,n)=>new Date(Date.parse(date(base)+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);
const registrationFields=['customer_name','sdt','email','dia_chi','start_date','end_date','duration_days','ma_vd','trang_thai','is_consultation','is_deposit','deposit_amount','san_pham','gia_tien','courseBasePrice','checkoutStage','updatedAt'];
const registrationData=data=>Object.fromEntries(registrationFields.filter(k=>data?.[k]!==undefined).map(k=>[k,data[k]]));
function safeLink(link){try{const u=new URL(link);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}}
function access(user,id){permission(user,'customers');assertCustomer(user,id);const c=get('customers',id);if(!c)fail('Không tìm thấy khách hàng.',404);return c;}
function localPlan(c){return ((c.planCustomerId||c.customer_id)?get('study_plans',c.planCustomerId||c.customer_id):null)||all('study_plans').find(p=>p.customerId===c.id);}
async function record(c){const local=localPlan(c);if(c.origin==='taophacdo'||local?.publishedAt){const remote=await readLearner(local?.id||c.customer_id);if(!remote){put('learner_source_facts',{...get('learner_source_facts',c.id),id:c.id,status:'DELETED',learnerDeleted:true});return {data:null,remote:false,local:null,deleted:true};}return {data:remote,remote:true,local};}return {data:local?.customer||null,local,remote:false};}
function purchases(c){const orders=all('orders').filter(o=>o.customerId===c.id&&o.status!=='cancelled'&&(o.status!=='draft'||o.paid>0));const items=orders.flatMap(o=>o.items.map(i=>({...i,total:i.price*i.quantity,orderId:o.id})));const imported=Array.isArray(c.san_pham)?c.san_pham:[];return {items:[...items,...imported.map(i=>({productId:i.productId,id_sp:i.id_sp,name:i.ten_sp,quantity:i.so_luong,price:i.don_gia,total:i.thanh_tien,productType:i.productType}))],total:orders.reduce((n,o)=>n+o.total,0)+Number(c.gia_tien||0)};}
export async function learnerProfile(user,id){const c=access(user,id),r=await record(c),data=r.data,catalog=await readPlanCatalog();let attendance=[],tasks=[];
 if(data){if(r.remote){const facts={id:c.id,is_deposit:data.is_deposit,deposit_amount:data.deposit_amount,is_consultation:data.is_consultation,gia_tien:data.gia_tien,san_pham:data.san_pham,start_date:data.start_date,end_date:data.end_date,status:data.status,hasEffectivePlan:!!(data.link||data.video_date||data.is_customized),learnerDeleted:deletedLearner(data),sourceUpdatedAt:data.updated_at};if(get('learner_source_facts',c.id)?.sourceUpdatedAt!==data.updated_at||get('learner_source_facts',c.id)?.status!==data.status||get('learner_source_facts',c.id)?.learnerDeleted!==facts.learnerDeleted)put('learner_source_facts',facts);const activity=await readLearnerActivity(data.customer_id,data.is_customized);attendance=activity.attendance;tasks=activity.tasks;}else{attendance=all('attendance_logs').filter(a=>a.customer_id===data.customer_id);tasks=r.local.tasks||[];}if(!data.is_customized)tasks=planFor(data,(await readPlanCatalog()).tasks,[]);}
 let groupWarning='';for(const contact of all('conversations').filter(v=>v.customerId===c.id&&v.threadType!==1&&v.externalUserId&&!v.deletedAt)){try{assertChannel(user,contact.connectionId);const ch=get('connections',contact.connectionId);if(ch?.provider==='zalo_personal'&&ch.mode==='api'&&ch.status==='connected'&&(!contact.commonGroupsSyncedAt||Date.now()-Date.parse(contact.commonGroupsSyncedAt)>300000))await syncCommonGroups(contact.connectionId,String(contact.externalUserId));}catch{groupWarning='Chưa cập nhật được nhóm chung từ Zalo; đang hiển thị danh sách đã đồng bộ.';}}
 const progressCustomer={...c,...(data?{status:data.status,is_deposit:data.is_deposit,deposit_amount:data.deposit_amount}:{}),...(r.deleted?{learnerDeleted:true}:{})};const stage=progressFor({journeys:all('journeys'),orders:all('orders'),chat_reminders:all('chat_reminders'),chatPlanSummaries:data?[{customerId:c.id,startDate:data.start_date,endDate:data.end_date,status:r.local&&!r.remote?studyPlanStatus(r.local,get('orders',r.local.lastOrderId)):data.status}]:[]},progressCustomer).stage;
 const products=all('products').filter(p=>p.active!==false).map(p=>({id:p.id,id_sp:p.id_sp,name:p.name,price:p.price,productType:p.productType,availableStock:(!p.productType||p.productType==='physical')?Math.max(0,Number(p.stock||0)-Number(p.reserved||0)):null}));for(const p of catalog.products)if(!all('products').some(x=>x.id_sp===p.id_sp))products.push({id:'catalog:'+p.id_sp,id_sp:p.id_sp,name:p.ten_sp,price:p.gia_ban,productType:p.productType||(isCourse(p)?'course':'physical'),availableStock:(p.productType||(isCourse(p)?'course':'physical'))==='physical'?0:null});
 const conversations=new Set(all('conversations').filter(v=>v.customerId===c.id&&v.threadType!==1).map(v=>v.id));const phoneMessage=all('messages').filter(m=>m.direction==='incoming'&&conversations.has(m.conversationId)).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).find(m=>phonesIn(m.text).length===1);
 const registration={...registrationData(data),...registrationData(c.learnerRegistration)};const bought=purchases(r.remote?{...c,san_pham:data.san_pham,gia_tien:data.gia_tien}:c);const savedItems=registration.san_pham||[],seen=new Set(savedItems.map(i=>i.productId||i.id_sp||i.ten_sp));const added=new Map();for(const i of bought.items){const key=i.productId||i.id_sp||i.name;if(seen.has(key))continue;const addedKey=key+':'+(i.price??i.total/i.quantity),prev=added.get(addedKey);if(prev){prev.so_luong+=i.quantity;prev.thanh_tien+=i.total;}else added.set(addedKey,{productId:i.productId,id_sp:i.id_sp,ten_sp:i.name,so_luong:i.quantity,don_gia:i.price??i.total/i.quantity,thanh_tien:i.total,productType:i.productType});}if(savedItems.length||added.size)registration.san_pham=[...savedItems,...added.values()];
 return {groupWarning,commonGroups:commonGroups(user,c.id),registration:Object.keys(registration).length?registration:null,customer:{id:c.id,name:c.name,phone:c.phone||data?.sdt||phonesIn(phoneMessage?.text)[0]||'',email:c.email||data?.email||'',address:c.address||data?.dia_chi||'',note:c.note||data?.note||'',version:c.version},products,catalogWarning:catalog.warning||'',stage,hasPlan:!!data&&!deletedLearner(data),version:r.remote?data?.updated_at:r.local?.version||0,plan:data&&!deletedLearner(data)?{startDate:data.start_date,endDate:data.end_date,durationDays:data.duration_days,googleAuth:data.require_google_auth!==false,deviceLimit:data.require_device_limit!==false,link:safeLink(data.link),remainingDays:data.end_date?Math.max(0,Math.ceil((Date.parse(data.end_date+'T23:59:59+07:00')-Date.now())/86400000)):0}:null,attendance:{opened:new Set(attendance.map(a=>a.access_date)).size,total:new Set(tasks.filter(t=>!t.is_deleted).map(t=>t.day)).size||Number(data?.duration_days||0),rows:attendance.map(a=>({date:a.access_date,createdAt:a.created_at||a.createdAt})).sort((a,b)=>String(b.date).localeCompare(String(a.date)))},purchases:purchases(r.remote?{...c,san_pham:data.san_pham,gia_tien:data.gia_tien}:c)};
}
async function quickOrderContext(user,c){
 const catalog=await readPlanCatalog(),local=all('products').filter(p=>p.active!==false);
 const products=local.map(p=>({id:p.id,name:p.name,price:p.price,productType:p.productType,availableStock:(!p.productType||p.productType==='physical')?Math.max(0,Number(p.stock||0)-Number(p.reserved||0)):null}));
 for(const p of catalog.products)if(!local.some(x=>x.id_sp===p.id_sp))products.push({id:'catalog:'+p.id_sp,name:p.ten_sp,price:p.gia_ban,productType:p.productType||(isCourse(p)?'course':'physical'),availableStock:(p.productType||(isCourse(p)?'course':'physical'))==='physical'?0:null});
 const ids=new Set(all('conversations').filter(v=>v.customerId===c.id&&v.threadType!==1&&!v.deletedAt).filter(v=>{try{assertChannel(user,v.connectionId);return true;}catch{return false;}}).map(v=>v.id));
 const found=latestContact(all('messages').filter(m=>ids.has(m.conversationId)));
 return {customer:{id:c.id,name:c.name,phone:found.phone||c.phone||'',email:c.email||'',address:found.address||c.address||'',version:c.version},products,catalogWarning:catalog.warning||''};
}
function contact(input){const result={};for(const k of ['name','phone','address','email','note'])if(input[k]!==undefined)result[k]=String(input[k]||'').trim().slice(0,k==='address'?1000:k==='note'?2000:200);if(input.name!==undefined&&!result.name)fail('Nhập tên khách hàng.');if(result.name)result.nameEditedLocally=true;if(result.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(result.email))fail('Email không hợp lệ.');return result;}
async function update(user,c,input){if(input.customerVersion!==c.version)fail('Hồ sơ đã thay đổi. Mở lại hồ sơ.',409);const r=await record(c);if(input.version!==(r.remote?r.data?.updated_at:r.local?.version||0))fail('Phác đồ đã thay đổi. Mở lại hồ sơ.',409);const patch={},contacts=contact(input),existingRegistration={...registrationData(r.data),...registrationData(c.learnerRegistration)},oldStage=progressFor({...progressState(),chatPlanSummaries:r.data?[{customerId:c.id,startDate:r.data.start_date,endDate:r.data.end_date,status:r.local&&!r.remote?studyPlanStatus(r.local,get('orders',r.local.lastOrderId)):r.data.status}]:progressState().chatPlanSummaries},{...c,...(r.data?{is_deposit:r.data.is_deposit,deposit_amount:r.data.deposit_amount,is_consultation:r.data.is_consultation,gia_tien:r.data.gia_tien,san_pham:r.data.san_pham}:{})}).stage;const effectiveStage=input.action==='registration'&&input.stage==='DEPOSIT'&&input.isDeposit===false?(input.unconsulted===true?'NEW':'CONSULTED'):input.stage;const changing=['stage','registration'].includes(input.action);if(changing&&stageRank(effectiveStage)<stageRank(oldStage)&&input.confirmDowngrade!==true)fail('Học viên đang ở '+learnerStages[oldStage].name+'. Xác nhận hạ tiến trình trước khi lưu.',409);if(input.reviewId&&(input.action!=='registration'||!['DEPOSIT','PAID'].includes(input.stage)))fail('Lưu kết quả đặt cọc hoặc đủ tiền để hoàn tất câu hỏi tư vấn.');if(input.reviewId)checkConsultation(user,input.reviewId,c.id,input.reviewVersion);let registration=null;let fee=0,order=null,courseIndex=-1;
 if(input.action==='registration'){
  if(!learnerStages[input.stage])fail('Tiến trình không hợp lệ.');if(['STUDYING','EXPIRING','EXPIRED'].includes(input.stage)&&!r.data)fail('Cần có phác đồ học viên trước khi cập nhật bước học.');
  if(!contacts.name)fail('Nhập tên học viên.');
  const duration=number(input.durationDays,'Số ngày tập',1,3650);if(!Number.isInteger(duration))fail('Số ngày tập phải là số nguyên.');
  const start=date(input.startDate),products=(input.items||[]);if(!Array.isArray(products)||products.length>100)fail('Danh sách sản phẩm không hợp lệ.');
  const catalog=await readPlanCatalog(),local=all('products');
  const san_pham=products.map(i=>{const saved=(existingRegistration.san_pham||[]).find(x=>x.productId===i.productId||x.id_sp===i.productId||'catalog:'+x.id_sp===i.productId);const p=local.find(p=>p.id===i.productId&&p.active!==false)||catalog.products.find(p=>'catalog:'+p.id_sp===i.productId)||(saved?{id:saved.id_sp,name:saved.ten_sp,productType:saved.productType}:null);if(!p)fail('Sản phẩm không còn trong danh mục.');const q=number(i.quantity,'Số lượng',1,10000),price=number(i.price,'Đơn giá',0,1e12);if(!Number.isInteger(q))fail('Số lượng phải là số nguyên.');return {productId:i.productId,id_sp:p.id_sp||p.id,productType:p.productType||(isCourse(p)?'course':'physical'),ten_sp:p.name||p.ten_sp,so_luong:q,don_gia:price,thanh_tien:q*price};});
  registration={...existingRegistration,checkoutStage:effectiveStage,customer_name:contacts.name,sdt:contacts.phone||'',email:contacts.email||'',dia_chi:contacts.address||'',start_date:start,end_date:addDays(start,duration),duration_days:duration,ma_vd:String(input.tracking||'').slice(0,100),trang_thai:number(input.assignment||0,'Trạng thái gán',0,1),is_consultation:input.unconsulted!==true,is_deposit:input.isDeposit===undefined?(existingRegistration.is_deposit??input.stage==='DEPOSIT'):input.isDeposit===true,deposit_amount:number(input.depositAmount??existingRegistration.deposit_amount??(input.stage==='DEPOSIT'?500000:0),'Tiền đặt cọc',0,1e12),courseBasePrice:number(input.courseBasePrice??existingRegistration.courseBasePrice??0,'Học phí gốc',0,1e12),san_pham,gia_tien:san_pham.reduce((n,i)=>n+i.thanh_tien,0),updatedAt:now()};
  if(r.data){for(const [key,value] of Object.entries({sdt:contacts.phone,email:contacts.email,dia_chi:contacts.address,start_date:start,end_date:addDays(start,duration),duration_days:duration}))if(value!==undefined&&r.data[key]!==value)patch[key]=value;}
 }else if(input.action==='contact'){Object.assign(patch,{...(contacts.phone!==undefined?{sdt:contacts.phone}:{}),...(contacts.email!==undefined?{email:contacts.email}:{}),...(contacts.address!==undefined?{dia_chi:contacts.address}:{})});}
 else if(input.action==='stage'){if(!learnerStages[input.stage])fail('Tiến trình không hợp lệ.');if(['STUDYING','EXPIRING','EXPIRED'].includes(input.stage)&&!r.data)fail('Cần có phác đồ học viên trước khi cập nhật bước học.');}
 else {if(!r.data)fail('Học viên chưa có phác đồ.',409);if(input.action==='security'){if(typeof input.googleAuth!=='boolean'||typeof input.deviceLimit!=='boolean')fail('Cấu hình bảo mật không hợp lệ.');patch.require_google_auth=input.googleAuth;patch.require_device_limit=input.deviceLimit;}
  else if(input.action==='dates'){patch.start_date=date(input.startDate);patch.end_date=date(input.endDate);if(patch.end_date<=patch.start_date)fail('Ngày kết thúc phải sau ngày bắt đầu.');patch.duration_days=(Date.parse(patch.end_date)-Date.parse(patch.start_date))/86400000;if(patch.duration_days>3650)fail('Thời hạn học tối đa 3650 ngày.');}
  else if(input.action==='renew'){const n=number(input.days,'Số ngày',1,3650);if(!Number.isInteger(n))fail('Số ngày phải là số nguyên.');const base=date(input.baseDate);patch.end_date=addDays(base,n);patch.start_date=r.data.start_date;if(patch.end_date<=r.data.end_date||patch.end_date<=patch.start_date)fail('Ngày kết thúc mới phải sau thời hạn hiện tại.');patch.duration_days=(Date.parse(patch.end_date)-Date.parse(patch.start_date))/86400000;fee=number(input.amount||0,'Tiền gia hạn',0,1e12);
   if(fee){permission(user,'orders');if(r.remote||r.local?.createdWithoutPayment&&!r.local.lastOrderId){const catalog=await readPlanCatalog(),products=(r.data.san_pham||[]).map(p=>({...p}));courseIndex=products.findIndex(p=>catalog.products.some(k=>k.id_sp===p.id_sp&&isCourse(k))||isCourse(p));if(courseIndex<0)fail('Chưa xác định được sản phẩm khóa học trong hồ sơ.');const item=products[courseIndex],q=Number(item.so_luong||1);item.thanh_tien=Number(item.thanh_tien||Number(item.don_gia)*q)+fee;item.don_gia=item.thanh_tien/q;patch.san_pham=products;patch.gia_tien=Number(r.data.gia_tien||0)+fee;}
    else{order=get('orders',r.local.lastOrderId);courseIndex=order?.items.findIndex(i=>i.productType==='course')??-1;if(!order||order.status==='cancelled'||courseIndex<0)fail('Không tìm thấy đơn khóa học để cộng tiền gia hạn.');}}
  }else fail('Thao tác không hợp lệ.');
 }
 // Remote writes use the source updated_at to avoid overwriting changes from QL phác đồ.
 if(r.remote&&Object.keys(patch).length)await writeLearner(r.data.customer_id,input.version,patch);
 transaction(()=>{const current=get('customers',c.id);if(current.version!==c.version)fail('Hồ sơ đã thay đổi.',409);put('customers',{...c,...contacts,...(registration?{learnerRegistration:registration}:{}),...(patch.end_date&&c.learnerProgress?{learnerProgress:{...c.learnerProgress,manualOverride:false}}:{}),...(r.remote?patch:{}),...(['stage','registration'].includes(input.action)?{learnerProgress:{...c.learnerProgress,stage:effectiveStage,source:'staff',manualOverride:true,planOverride:input.confirmDowngrade===true,updatedAt:now(),updatedBy:user.id}}:{})},c.version);
  if(r.local&&Object.keys(patch).length){const p={...r.local,customer:{...r.local.customer,...patch}};if(order&&fee){const items=order.items.map(i=>({...i}));items[courseIndex].price+=fee/items[courseIndex].quantity;const updated=put('orders',{...order,items,subtotal:order.subtotal+fee,total:order.total+fee,paymentStatus:order.paid>=order.total+fee?'paid':order.paid?'partial':'unpaid'});syncPaymentOrder(updated);p.accessPaymentFloor=r.local.accessPaymentFloor??order.total;}put('study_plans',p,r.local.version);const j=all('journeys').find(j=>j.customerId===c.id);if(j&&patch.end_date)put('journeys',{...j,startDate:patch.start_date,endDate:patch.end_date});}
  if(['stage','registration'].includes(input.action))put('journey_events',{customerId:c.id,from:oldStage,to:effectiveStage,actor:user.id,source:'chat_progress',reason:'Cập nhật từ hồ sơ học viên'});
  if(input.reviewId)finishConsultation(user,input.reviewId,effectiveStage);
  if(input.action==='renew')put('learner_renewals',{customerId:c.id,baseDate:input.baseDate,days:Number(input.days),amount:fee,previousEndDate:r.data.end_date,endDate:patch.end_date,orderId:order?.id||null,actor:user.id});audit(user.id,'learner_'+input.action,c.id,{endDate:patch.end_date,amount:fee});
 });return learnerProfile(user,c.id);
}
export async function learnerRoute(path,method,input,user){const relationships=relationshipsRoute(path,method,input,user);if(relationships!==undefined)return relationships;const m=path.match(/^\/api\/care\/customers\/([^/]+)\/learner(?:\/(sources|copy|order|plan|preview))?$/);if(!m)return undefined;const c=access(user,decodeURIComponent(m[1])),action=m[2];
 if(!action&&method==='GET')return learnerProfile(user,c.id);
 if(!action&&method==='PATCH')return update(user,c,input);
 if(action==='preview'&&method==='GET'){const r=await record(c);if(!r.data)fail('Học viên chưa có phác đồ.',404);const customer={...r.data,...(r.remote?await readPlanProfile(r.data.customer_id):{})};let tasks=r.local?.tasks||[];if(r.remote)tasks=(await readLearnerActivity(customer.customer_id,customer.is_customized)).tasks;if(!customer.is_customized)tasks=planFor(customer,(await readPlanCatalog()).tasks,[]);return {customer,tasks};}
 if(action==='plan'&&method==='GET'){const r=await record(c),p=r.data;const link=safeLink(p?.link||c.link);const previewUrl=p?'/plan-preview/index.html?customer='+encodeURIComponent(c.id):'';return {hasPlan:!!p,previewUrl,name:p?.customer_name||c.name,link,startDate:p?.start_date,endDate:p?.end_date,tasks:(r.local?.tasks||[]).map(t=>({day:t.day,title:t.title,link:safeLink(t.link)}))};}
 if(action==='sources'&&method==='GET')return listPlanSources(user,c.id);
 if(action==='copy'&&method==='POST'){if(input.customerVersion!==c.version)fail('Hồ sơ đã thay đổi.',409);const source=await getPlanSource(user,c.id,input.sourceId);const copy=Object.fromEntries(['note','chewing_status','sidebar_blocks_json','app_title','app_slogan','duration_days','video_date','ma_vd','is_customized','require_google_auth','require_device_limit'].map(k=>[k,source.customer[k]]));const target=await record(c);if(target.data)fail('Học viên đã có phác đồ. Mở trình phác đồ để chỉnh sửa.',409);transaction(()=>{put('plan_drafts',{id:c.id,customer:copy,tasks:source.tasks,sourceId:input.sourceId,actor:user.id});audit(user.id,'learner_plan_copied',c.id,{sourceId:input.sourceId});});return {copied:true};}
 if(action==='order'&&method==='GET')return quickOrderContext(user,c);
 if(action==='order'&&method==='POST'){if(input.customerVersion!==c.version)fail('Hồ sơ đã thay đổi.',409);const contacts=contact({...input,name:undefined}),catalog=await readPlanCatalog();return transaction(()=>{const items=(input.items||[]).map(i=>{if(!i.productId?.startsWith('catalog:'))return i;const source=catalog.products.find(p=>p.id_sp===i.productId.slice(8));if(!source)fail('Sản phẩm không còn trong danh mục.');const id='plan-product:'+source.id_sp;if(!get('products',id))put('products',{id,id_sp:source.id_sp,name:source.ten_sp,sku:source.id_sp,price:source.gia_ban,cost:source.gia_nhap||0,stock:0,reserved:0,active:true,productType:source.productType||(isCourse(source)?'course':'physical')});return {...i,productId:id};});const result=createOrder(user,{...input,items,customerId:c.id,phone:contacts.phone||c.phone,address:contacts.address||c.address,shippingFee:input.freeShipping?0:input.shippingFee},{allowCustomPrice:true,allowDraftAddress:true});put('customers',{...c,...contacts},c.version);return result;});}
}
