import {listPlanSources,getPlanSource} from './plan-sources.mjs';
import {studyPlanStatus} from './plan-access.mjs';
import {all,get,put,transaction,audit,now} from './store.mjs';
import {permission,fail,number,createOrder} from './domain.mjs';
import {assertCustomer,planFor,phonesIn,syncPaymentOrder} from './taophacdo.mjs';
import {readLearner,writeLearner,readLearnerActivity,readPlanCatalog,readPlanProfile} from './supabase.mjs';
import {learnerStages,progressFor} from '../public/learner-progress.js';

const date=value=>{const parsed=Date.parse(value+'T00:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(value||'')||!Number.isFinite(parsed)||new Date(parsed).toISOString().slice(0,10)!==value)fail('Ngày không hợp lệ.');return value;};
const isCourse=p=>p.productType==='course'||p.id_sp==='SP1768731546380'||/khóa học|khoá học|khoa hoc/i.test(p.ten_sp||p.name||'');
const addDays=(base,n)=>new Date(Date.parse(date(base)+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);
function safeLink(link){try{const u=new URL(link);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}}
function access(user,id){permission(user,'customers');assertCustomer(user,id);const c=get('customers',id);if(!c)fail('Không tìm thấy khách hàng.',404);return c;}
function localPlan(c){return ((c.planCustomerId||c.customer_id)?get('study_plans',c.planCustomerId||c.customer_id):null)||all('study_plans').find(p=>p.customerId===c.id);}
async function record(c){const local=localPlan(c);if(c.origin==='taophacdo'||local?.publishedAt){const remote=await readLearner(local?.id||c.customer_id);if(!remote)fail('Không tải được hồ sơ học viên từ QL phác đồ.',422);return {data:remote,remote:true,local};}return {data:local?.customer||null,local,remote:false};}
function purchases(c){const orders=all('orders').filter(o=>o.customerId===c.id&&o.status!=='cancelled'&&(o.status!=='draft'||o.paid>0));const items=orders.flatMap(o=>o.items.map(i=>({...i,total:i.price*i.quantity,orderId:o.id})));const imported=Array.isArray(c.san_pham)?c.san_pham:[];return {items:[...items,...imported.map(i=>({name:i.ten_sp,quantity:i.so_luong,total:i.thanh_tien}))],total:orders.reduce((n,o)=>n+o.total,0)+Number(c.gia_tien||0)};}
export async function learnerProfile(user,id){const c=access(user,id),r=await record(c),data=r.data,catalog=await readPlanCatalog();let attendance=[],tasks=[];
 if(data){if(r.remote){const activity=await readLearnerActivity(data.customer_id,data.is_customized);attendance=activity.attendance;tasks=activity.tasks;}else{attendance=all('attendance_logs').filter(a=>a.customer_id===data.customer_id);tasks=r.local.tasks||[];}if(!data.is_customized)tasks=planFor(data,(await readPlanCatalog()).tasks,[]);}
 const stage=progressFor({journeys:all('journeys'),orders:all('orders'),chatPlanSummaries:data?[{customerId:c.id,startDate:data.start_date,endDate:data.end_date,status:r.local&&!r.remote?studyPlanStatus(r.local,get('orders',r.local.lastOrderId)):data.status}]:[]},c).stage;
 const products=all('products').filter(p=>p.active!==false).map(p=>({id:p.id,name:p.name,price:p.price,productType:p.productType}));for(const p of catalog.products)if(!all('products').some(x=>x.id_sp===p.id_sp))products.push({id:'catalog:'+p.id_sp,name:p.ten_sp,price:p.gia_ban,productType:p.productType||(isCourse(p)?'course':'physical')});
 const conversations=new Set(all('conversations').filter(v=>v.customerId===c.id&&v.threadType!==1).map(v=>v.id));const phoneMessage=all('messages').filter(m=>m.direction==='incoming'&&conversations.has(m.conversationId)).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).find(m=>phonesIn(m.text).length===1);
 return {customer:{id:c.id,name:c.name,phone:c.phone||phonesIn(phoneMessage?.text)[0]||'',email:c.email||'',address:c.address||'',version:c.version},products,catalogWarning:catalog.warning||'',stage,hasPlan:!!data,version:r.remote?data?.updated_at:r.local?.version||0,plan:data?{startDate:data.start_date,endDate:data.end_date,durationDays:data.duration_days,googleAuth:data.require_google_auth!==false,deviceLimit:data.require_device_limit!==false,link:safeLink(data.link),remainingDays:data.end_date?Math.max(0,Math.ceil((Date.parse(data.end_date+'T23:59:59+07:00')-Date.now())/86400000)):0}:null,attendance:{opened:new Set(attendance.map(a=>a.access_date)).size,total:new Set(tasks.filter(t=>!t.is_deleted).map(t=>t.day)).size||Number(data?.duration_days||0),rows:attendance.map(a=>({date:a.access_date,createdAt:a.created_at||a.createdAt})).sort((a,b)=>String(b.date).localeCompare(String(a.date)))},purchases:purchases(r.remote?{...c,san_pham:data.san_pham,gia_tien:data.gia_tien}:c)};
}
function contact(input){const result={};for(const k of ['phone','address','email'])if(input[k]!==undefined)result[k]=String(input[k]||'').trim().slice(0,k==='address'?1000:200);if(result.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(result.email))fail('Email không hợp lệ.');return result;}
async function update(user,c,input){if(input.customerVersion!==c.version)fail('Hồ sơ đã thay đổi. Mở lại hồ sơ.',409);const r=await record(c);if(input.version!==(r.remote?r.data?.updated_at:r.local?.version||0))fail('Phác đồ đã thay đổi. Mở lại hồ sơ.',409);const patch={},contacts=contact(input);let fee=0,order=null,courseIndex=-1;
 if(input.action==='contact'){Object.assign(patch,{...(contacts.phone!==undefined?{sdt:contacts.phone}:{}),...(contacts.email!==undefined?{email:contacts.email}:{}),...(contacts.address!==undefined?{dia_chi:contacts.address}:{})});}
 else if(input.action==='stage'){if(!learnerStages[input.stage])fail('Tiến trình không hợp lệ.');if(['STUDYING','EXPIRING','EXPIRED'].includes(input.stage)&&!r.data)fail('Cần có phác đồ học viên trước khi cập nhật bước học.');}
 else {if(!r.data)fail('Học viên chưa có phác đồ.',409);if(input.action==='security'){if(typeof input.googleAuth!=='boolean'||typeof input.deviceLimit!=='boolean')fail('Cấu hình bảo mật không hợp lệ.');patch.require_google_auth=input.googleAuth;patch.require_device_limit=input.deviceLimit;}
  else if(input.action==='dates'){patch.start_date=date(input.startDate);patch.end_date=date(input.endDate);if(patch.end_date<=patch.start_date)fail('Ngày kết thúc phải sau ngày bắt đầu.');patch.duration_days=(Date.parse(patch.end_date)-Date.parse(patch.start_date))/86400000;if(patch.duration_days>3650)fail('Thời hạn học tối đa 3650 ngày.');}
  else if(input.action==='renew'){const n=number(input.days,'Số ngày',1,3650);if(!Number.isInteger(n))fail('Số ngày phải là số nguyên.');const base=date(input.baseDate);patch.end_date=addDays(base,n);patch.start_date=r.data.start_date;if(patch.end_date<=r.data.end_date||patch.end_date<=patch.start_date)fail('Ngày kết thúc mới phải sau thời hạn hiện tại.');patch.duration_days=(Date.parse(patch.end_date)-Date.parse(patch.start_date))/86400000;fee=number(input.amount||0,'Tiền gia hạn',0,1e12);
   if(fee){permission(user,'orders');if(r.remote||r.local?.createdWithoutPayment&&!r.local.lastOrderId){const catalog=await readPlanCatalog(),products=(r.data.san_pham||[]).map(p=>({...p}));courseIndex=products.findIndex(p=>catalog.products.some(k=>k.id_sp===p.id_sp&&isCourse(k))||isCourse(p));if(courseIndex<0)fail('Chưa xác định được sản phẩm khóa học trong hồ sơ.');const item=products[courseIndex],q=Number(item.so_luong||1);item.thanh_tien=Number(item.thanh_tien||Number(item.don_gia)*q)+fee;item.don_gia=item.thanh_tien/q;patch.san_pham=products;patch.gia_tien=Number(r.data.gia_tien||0)+fee;}
    else{order=get('orders',r.local.lastOrderId);courseIndex=order?.items.findIndex(i=>i.productType==='course')??-1;if(!order||order.status==='cancelled'||courseIndex<0)fail('Không tìm thấy đơn khóa học để cộng tiền gia hạn.');}}
  }else fail('Thao tác không hợp lệ.');
 }
 // Remote writes use the source updated_at to avoid overwriting changes from QL phác đồ.
 if(r.remote&&Object.keys(patch).length)await writeLearner(r.data.customer_id,input.version,patch);
 transaction(()=>{const current=get('customers',c.id);if(current.version!==c.version)fail('Hồ sơ đã thay đổi.',409);put('customers',{...c,...contacts,...(patch.end_date&&c.learnerProgress?{learnerProgress:{...c.learnerProgress,manualOverride:false}}:{}),...(r.remote?patch:{}),...(input.action==='stage'?{learnerProgress:{...c.learnerProgress,stage:input.stage,source:'staff',manualOverride:true,updatedAt:now(),updatedBy:user.id}}:{})},c.version);
  if(r.local&&Object.keys(patch).length){const p={...r.local,customer:{...r.local.customer,...patch}};if(order&&fee){const items=order.items.map(i=>({...i}));items[courseIndex].price+=fee/items[courseIndex].quantity;const updated=put('orders',{...order,items,subtotal:order.subtotal+fee,total:order.total+fee,paymentStatus:order.paid>=order.total+fee?'paid':order.paid?'partial':'unpaid'});syncPaymentOrder(updated);p.accessPaymentFloor=r.local.accessPaymentFloor??order.total;}put('study_plans',p,r.local.version);const j=all('journeys').find(j=>j.customerId===c.id);if(j&&patch.end_date)put('journeys',{...j,startDate:patch.start_date,endDate:patch.end_date});}
  if(input.action==='stage')put('journey_events',{customerId:c.id,from:c.learnerProgress?.stage||'NEW',to:input.stage,actor:user.id,source:'chat_progress',reason:'Cập nhật từ hồ sơ học viên'});
  if(input.action==='renew')put('learner_renewals',{customerId:c.id,baseDate:input.baseDate,days:Number(input.days),amount:fee,previousEndDate:r.data.end_date,endDate:patch.end_date,orderId:order?.id||null,actor:user.id});audit(user.id,'learner_'+input.action,c.id,{endDate:patch.end_date,amount:fee});
 });return learnerProfile(user,c.id);
}
export async function learnerRoute(path,method,input,user){const m=path.match(/^\/api\/care\/customers\/([^/]+)\/learner(?:\/(sources|copy|order))?$/);if(!m)return undefined;const c=access(user,decodeURIComponent(m[1])),action=m[2];
 if(!action&&method==='GET')return learnerProfile(user,c.id);
 if(!action&&method==='PATCH')return update(user,c,input);
 if(action==='sources'&&method==='GET')return listPlanSources(user,c.id);
 if(action==='copy'&&method==='POST'){if(input.customerVersion!==c.version)fail('Hồ sơ đã thay đổi.',409);const source=await getPlanSource(user,c.id,input.sourceId);const copy=Object.fromEntries(['note','chewing_status','sidebar_blocks_json','app_title','app_slogan','duration_days','video_date','ma_vd','is_customized','require_google_auth','require_device_limit'].map(k=>[k,source.customer[k]]));const target=await record(c);if(target.data)fail('Học viên đã có phác đồ. Mở trình phác đồ để chỉnh sửa.',409);transaction(()=>{put('plan_drafts',{id:c.id,customer:copy,tasks:source.tasks,sourceId:input.sourceId,actor:user.id});audit(user.id,'learner_plan_copied',c.id,{sourceId:input.sourceId});});return {copied:true};}
 if(action==='order'&&method==='POST'){if(input.customerVersion!==c.version)fail('Hồ sơ đã thay đổi.',409);const contacts=contact(input),catalog=await readPlanCatalog();return transaction(()=>{const items=(input.items||[]).map(i=>{if(!i.productId?.startsWith('catalog:'))return i;const source=catalog.products.find(p=>p.id_sp===i.productId.slice(8));if(!source)fail('Sản phẩm không còn trong danh mục.');const id='plan-product:'+source.id_sp;if(!get('products',id))put('products',{id,id_sp:source.id_sp,name:source.ten_sp,sku:source.id_sp,price:source.gia_ban,cost:source.gia_nhap||0,stock:0,reserved:0,active:true,productType:source.productType||(isCourse(source)?'course':'physical')});return {...i,productId:id};});const result=createOrder(user,{...input,items,customerId:c.id,phone:contacts.phone||c.phone,address:contacts.address||c.address,shippingFee:input.freeShipping?0:input.shippingFee},{allowCustomPrice:true});put('customers',{...c,...contacts},c.version);return result;});}
}
