import {all,get,put,audit} from './store.mjs';
import {permission,fail,required} from './domain.mjs';
import {assertChannel,permittedChannels} from './taophacdo.mjs';
export function usageFor(a,messages=all('messages'),publications=all('publications')){const events=[...messages.filter(m=>m.direction==='outgoing'&&['accepted','sent','delivered'].includes(m.status)&&(m.attachments||[]).some(x=>x.assetId===a.id||x.url===a.url)),...publications.filter(p=>['published','manually_confirmed'].includes(p.status)&&(p.assets||[]).includes(a.id))];return {count:events.length,lastAt:events.map(x=>x.publishedAt||x.createdAt).sort().at(-1)||null};}
export function mediaReferences(id){return ['contents','publications','templates'].flatMap(kind=>all(kind).filter(r=>(r.assets||r.assetIds||[]).includes(id)||(r.blocks||[]).some(b=>(b.assetIds||[]).includes(id))).map(r=>({kind,id:r.id,name:r.name||r.title||r.id})));}
export async function mediaRoute(path,method,input,user){
 const m=path.match(/^\/api\/media\/(assets|categories)(?:\/([^/]+))?$/);if(!m)return;
 const [,type,id]=m;permission(user,'read');const kind=type==='assets'?'assets':'media_categories',p=id?get(kind,id):null;if(id&&!p)fail('Không tìm thấy media/danh mục.',404);if(p?.connectionId)assertChannel(user,p.connectionId);
 if(method==='GET')return type==='assets'?{...p,usage:usageFor(p),references:mediaReferences(id).filter(r=>{const allowed=permittedChannels(user),record=get(r.kind,r.id);return !allowed||(!record.connectionId||allowed.has(record.connectionId))&&(record.channels||[]).every(id=>allowed.has(id));})}:all(kind);
 if(type==='assets'&&input.favorite!==undefined){if(method!=='PATCH'||typeof input.favorite!=='boolean')fail('Yêu thích không hợp lệ.');const key='media-favorites-'+user.id,old=get('settings',key)||{id:key,ids:[]};const ids=new Set(old.ids);input.favorite?ids.add(id):ids.delete(id);put('settings',{...old,ids:[...ids]});return {ok:true};}
 permission(user,'assets');if(method!=='POST'&&method!=='PATCH')fail('Thao tác không hỗ trợ.');if(type==='assets'&&!id)fail('Tải tệp qua chức năng tải lên.');if(p&&input.version!==p.version)fail('Dữ liệu đã thay đổi, tải lại trước khi lưu.',409);
 const next={...p,name:required(input.name??p?.name,'Tên',200),description:String(input.description??p?.description??'').slice(0,2000),active:input.active===undefined?p?.active!==false:input.active!==false};
 if(type==='categories'){next.order=Number(input.order||0);if(!Number.isInteger(next.order)||Math.abs(next.order)>10000)fail('Thứ tự không hợp lệ.');}
 else {const refs=mediaReferences(id);if(!next.active&&refs.length&&!input.confirmDeactivate)fail('Media đang được tham chiếu. Xác nhận ngừng sử dụng; lịch sử và tệp vẫn được giữ.',409);next.categoryIds=input.categoryIds??p.categoryIds??[];if(!Array.isArray(next.categoryIds)||next.categoryIds.length>30||next.categoryIds.some(id=>!get('media_categories',id)))fail('Danh mục không hợp lệ.');next.tags=String(input.tags??(p.tags||[]).join(',')).split(',').map(x=>x.trim()).filter(Boolean).slice(0,30);next.scopes=input.scopes??p.scopes??['chat','post','template'];if(!Array.isArray(next.scopes)||!next.scopes.length||next.scopes.some(x=>!['chat','post','template'].includes(x)))fail('Phạm vi không hợp lệ.');for(const k of ['width','height','duration'])if(input[k]!==undefined){const n=Number(input[k]);if(!Number.isFinite(n)||n<0||n>1e7)fail('Kích thước/thời lượng không hợp lệ.');next[k]=n;}}
 const r=put(kind,next,p?input.version:undefined);audit(user.id,'media_updated',r.id,{kind});return r;
}
