import { randomUUID } from 'node:crypto';
import { all,get,put,transaction,audit,notification,now } from './store.mjs';
import { fail,permission,required,number } from './domain.mjs';
import { assertCustomer,planFor } from './taophacdo.mjs';

export function syncPlanHandoff(order){let h=all('plan_handoffs').find(h=>h.orderId===order.id);const eligible=order.total>0&&order.paid>=order.total&&order.status!=='cancelled';if(!eligible){if(h&&h.status!=='payment_review')put('plan_handoffs',{...h,status:'payment_review',reason:'Khoản tiền đã thay đổi. Cần xác nhận thu đủ trước khi tiếp tục.'});return null;}
 if(h){if(h.status==='payment_review')h=put('plan_handoffs',{...h,status:h.planVersion?'saved_local':'ready',reason:''});return h;}
 const c=get('customers',order.customerId);if(!c)return null;const canonicalId=c.origin==='taophacdo'?c.customer_id:(c.planCustomerId||'C-HUB-'+randomUUID().replaceAll('-','').slice(0,16).toUpperCase());if(!c.planCustomerId)put('customers',{...c,planCustomerId:canonicalId,...(c.origin==='taophacdo'?{}:{customer_id:canonicalId})});
 h=put('plan_handoffs',{orderId:order.id,orderCode:order.code,customerId:c.id,canonicalId,status:'ready',conversationId:order.conversationId||null,paidAmount:order.paid,source:'local_confirmed_payment',planVersion:0});audit('system','plan_handoff_ready',h.id,{orderId:order.id});notification('Đã nhận đủ tiền · sẵn tạo phác đồ',c.name+' · '+order.code,'phacdo');return h;
}
function access(user,id){permission(user,'customers');const h=get('plan_handoffs',id);if(!h)fail('Không tìm thấy hồ sơ bàn giao phác đồ.',404);assertCustomer(user,h.customerId);const order=get('orders',h.orderId);if(!order||order.paid<order.total||order.total<=0||order.status==='cancelled')fail('Đơn chưa thu đủ hoặc đã hoàn tiền. Không thể tiếp tục tạo phác đồ.',409);return {h,order,c:get('customers',h.customerId)};}
const profileKeys=['customer_name','sdt','email','dia_chi','note','chewing_status','start_date','end_date','duration_days','video_date','ma_vd','sidebar_blocks_json','app_title','app_slogan','is_customized'];
function orderProducts(order){return order.items.map(i=>({id_sp:get('products',i.productId)?.id_sp||i.sku,ten_sp:i.name,so_luong:i.quantity,don_gia:i.price,gia_nhap:get('products',i.productId)?.cost||0,thanh_tien:i.quantity*i.price}));}
function profile(h,order,c){const saved=get('study_plans',h.canonicalId);const payload={customer_id:h.canonicalId,customer_name:c.name,sdt:c.phone||'',email:c.email||'',dia_chi:c.address||'',note:'',chewing_status:'',start_date:c.start_date||new Date(Date.now()+7*3600000).toISOString().slice(0,10),duration_days:Number(c.duration_days||30),end_date:c.end_date||'',video_date:c.video_date||'',ma_vd:c.ma_vd||'',sidebar_blocks_json:[],app_title:'Phác đồ học tập cá nhân',app_slogan:'Đồng hành cùng bạn mỗi ngày',status:'ACTIVE',trang_thai:1,trang_thai_gan:'1',require_google_auth:true,require_device_limit:true,is_customized:c.is_customized===true,...saved?.customer,san_pham:orderProducts(order),gia_tien:order.total,token:'',link:''};return {payload,saved};}
function draftAccess(user,id){permission(user,'customers');const customerId=id.slice(6);assertCustomer(user,customerId);const c=get('customers',customerId);if(!c)fail('Không tìm thấy khách hàng.',404);const order=all('orders').filter(o=>o.customerId===c.id&&o.status!=='cancelled').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0]||{items:[],total:0,paid:0,code:'Chưa có đơn hàng'};return {c,order,h:{id,customerId:c.id,canonicalId:c.planCustomerId||c.customer_id||'',status:'draft'}};}
export function editorData(user,id){const draft=id.startsWith('draft:');const {h,order,c}=draft?draftAccess(user,id):access(user,id);const {payload,saved}=profile(h,order,c);const masters=all('master_video_tasks');const dates=[...new Map(masters.filter(t=>t.video_date).map(t=>[t.video_date+'|'+t.nhom,{video_date:t.video_date,nhom:t.nhom||''}])).values()].sort((a,b)=>b.video_date.localeCompare(a.video_date));return {handoff:h,order:{id:order.id,code:order.code,total:order.total,paid:order.paid},customer:payload,tasks:payload.is_customized?(saved?.tasks||all('customer_tasks').filter(t=>t.customer_id===c.customer_id&&!t.is_deleted)):[],dates,products:all('products').filter(p=>p.active!==false).map(p=>({id_sp:p.id_sp||p.sku,ten_sp:p.name,gia_ban:p.price,gia_nhap:p.cost,trang_thai:1})),version:saved?.version||0,mode:draft?'unpaid_draft':'local_workflow',paymentEvidence:all('payments').filter(p=>p.orderId===order.id).map(({amount,reference,method,createdAt})=>({amount,reference,method,createdAt}))};}
function safeUrl(value){if(!value)return '';let u;try{u=new URL(value);}catch{fail('Đường dẫn bài tập không hợp lệ.');}if(!['https:','http:'].includes(u.protocol))fail('Đường dẫn chỉ hỗ trợ http/https.');return u.href;}
function savePlan(user,id,input){const {h,order,c}=access(user,id);const {payload,saved}=profile(h,order,c);if((input.version??0)!==(saved?.version||0))fail('Phác đồ vừa được cập nhật. Tải lại để tránh ghi đè.',409);const incoming=input.customer||{};if(incoming.customer_id&&incoming.customer_id!==h.canonicalId)fail('Mã học viên không khớp đơn bàn giao.');if(incoming.gia_tien!==undefined&&Number(incoming.gia_tien)!==order.total)fail('Giá trị đơn đã được xác nhận. Điều chỉnh tiền tại Đơn hàng, không sửa trong phác đồ.');const next={...payload};for(const k of profileKeys)if(incoming[k]!==undefined)next[k]=incoming[k];next.customer_name=required(next.customer_name,'Tên học viên',200);next.sdt=required(next.sdt,'Số điện thoại',40);next.email=String(next.email||'').trim().slice(0,200);if(next.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(next.email))fail('Email không hợp lệ.');next.duration_days=number(next.duration_days,'Thời hạn học',1,730);if(!/^\d{4}-\d{2}-\d{2}$/.test(next.start_date)||!Number.isFinite(Date.parse(next.start_date)))fail('Chọn ngày bắt đầu.');next.end_date=new Date(Date.parse(next.start_date+'T00:00:00Z')+next.duration_days*86400000).toISOString().slice(0,10);next.note=String(next.note||'').slice(0,10000);next.chewing_status=String(next.chewing_status||'').slice(0,10000);next.dia_chi=String(next.dia_chi||'').slice(0,1000);next.app_title=String(next.app_title||'').slice(0,200);next.app_slogan=String(next.app_slogan||'').slice(0,500);next.is_customized=next.is_customized===true;
 if(!Array.isArray(next.sidebar_blocks_json)||next.sidebar_blocks_json.length>30)fail('Tối đa 30 khối bên cạnh.');next.sidebar_blocks_json=next.sidebar_blocks_json.map(b=>({id:String(b.id||randomUUID()),title:String(b.title||'').slice(0,200),content:String(b.content||'').slice(0,10000),type:b.type==='dark'?'dark':'default',video_link:safeUrl(b.video_link),is_chat:b.is_chat===true}));
 if(!Array.isArray(input.tasks)||input.tasks.length>1000)fail('Danh sách bài tập không hợp lệ.');let tasks=input.tasks.map((t,i)=>({id:String(t.id||randomUUID()),customer_id:h.canonicalId,day:number(t.day,'Ngày bài tập',1,730),type:required(t.type||'Bài bắt buộc','Loại bài',100),title:required(t.title,'Tên bài tập',300),detail:String(t.detail||'').slice(0,10000),link:safeUrl(t.link),nhom:next.ma_vd||'',sort_order:i,is_deleted:false}));
 // The upstream editor edits the first 30 days; preserve any later imported tasks.
 const late=(saved?.tasks||all('customer_tasks').filter(t=>t.customer_id===c.customer_id&&!t.is_deleted)).filter(t=>t.day>30);tasks=[...tasks.filter(t=>t.day<=30),...late];if(next.is_customized&&!tasks.length)fail('Thêm ít nhất một bài tập vào phác đồ tùy chỉnh.');if(!next.is_customized&&!all('master_video_tasks').some(t=>t.video_date===next.video_date&&(!next.ma_vd||t.nhom===next.ma_vd)))fail('Chọn đợt video/nhóm đã nhập, hoặc bật tùy chỉnh và thêm bài tập.');
 return transaction(()=>{put('customers',{...c,name:next.customer_name,phone:next.sdt,email:next.email,address:next.dia_chi,planCustomerId:h.canonicalId});const p=put('study_plans',{id:h.canonicalId,customerId:c.id,customer:next,tasks:next.is_customized?tasks:[],handoffId:id,lastOrderId:order.id,savedBy:user.id},saved?.version);put('plan_handoffs',{...h,status:'saved_local',planVersion:p.version,savedAt:now(),savedBy:user.id,reason:''});const prev=all('journeys').find(j=>j.customerId===c.id);put('journeys',{...prev,customerId:c.id,stage:prev&&['DANG_HOC','SAP_HET_HAN','DA_XONG'].includes(prev.stage)?prev.stage:'DONG_TIEN',startDate:next.start_date,endDate:next.end_date,assignee:prev?.assignee||user.id});if(h.conversationId)put('messages',{conversationId:h.conversationId,direction:'note',status:'internal',text:'Đã lưu phác đồ '+h.canonicalId+' · phiên bản '+p.version+' · '+next.duration_days+' ngày (localhost)',handoffId:h.id,actor:user.id});audit(user.id,'study_plan_saved',h.canonicalId,{orderId:order.id,version:p.version});return {...next,planVersion:p.version};});
}
export async function planRoute(path,method,input,user,url){
 if(path==='/api/plans/prepare'&&method==='POST'){permission(user,'customers');const order=get('orders',input.orderId);if(!order)fail('Không tìm thấy đơn.',404);assertCustomer(user,order.customerId);const h=syncPlanHandoff(order);if(!h)fail('Chỉ tạo phác đồ sau khi đã xác nhận nhận đủ tiền.',409);return h;}
 const match=path.match(/^\/api\/plans\/([^/]+)(?:\/(editor|master|save|preview|export))?$/);if(!match)return undefined;const id=decodeURIComponent(match[1]),action=match[2]||'editor';
 if(id.startsWith('draft:')){draftAccess(user,id);if(action==='editor'&&method==='GET')return editorData(user,id);if(action==='master'&&method==='GET')return all('master_video_tasks').filter(t=>t.video_date===url.searchParams.get('date')&&(!url.searchParams.get('group')||t.nhom===url.searchParams.get('group'))&&!t.is_deleted).sort((a,b)=>a.day-b.day||(a.sort_order||0)-(b.sort_order||0));fail('Hãy xác nhận nhận đủ tiền tại Đơn hàng, sau đó mở lại Tạo phác đồ để lưu hồ sơ học viên.',409);}
 if(action==='editor'&&method==='GET')return editorData(user,id);
 if(action==='master'&&method==='GET'){access(user,id);const date=url.searchParams.get('date'),group=url.searchParams.get('group');return all('master_video_tasks').filter(t=>t.video_date===date&&(!group||t.nhom===group)&&!t.is_deleted).sort((a,b)=>a.day-b.day||(a.sort_order||0)-(b.sort_order||0));}
 if(action==='save'&&method==='POST')return savePlan(user,id,input);
 if(['preview','export'].includes(action)&&method==='GET'){const {h,order,c}=access(user,id);const {payload,saved}=profile(h,order,c);if(!saved)fail('Phác đồ chưa được lưu.',409);const tasks=payload.is_customized?saved.tasks:planFor(payload,all('master_video_tasks'),[]);if(action==='preview')return {customer:payload,tasks,version:saved.version,mode:'local_workflow'};return {schema:'taophacdo.social-handoff.v1',handoffId:h.id,order:{code:order.code,total:order.total,paid:order.paid},paymentConfirmation:{source:'staff_confirmed_in_local_workspace',references:all('payments').filter(p=>p.orderId===order.id&&p.amount>0).map(p=>p.reference)},customer:Object.fromEntries(Object.entries(payload).filter(([k])=>!['token','link'].includes(k))),tasks,exportedAt:now(),note:'Hồ sơ bàn giao từ localhost; cần nhân viên có quyền kiểm tra trước khi lưu ở taophacdo.'};}
 return undefined;
}
