import ExcelJS from 'exceljs';
import {all,get,put,remove,transaction,audit} from './store.mjs';
import {permission,fail,required} from './domain.mjs';
import {assertChannel} from './taophacdo.mjs';
const key=v=>String(v||'').trim().normalize('NFC').toLocaleLowerCase('vi');
const order=v=>{const n=Number(v??1);if(!Number.isInteger(n)||n<1||n>9999)fail('STT từ 1 đến 9999.');return n;};
export function validateQuickReply(input,user,old=null){
 const shortcut=String(input.shortcut||'').trim().replace(/^\//,'');
 if(shortcut.length>40||/\s/.test(shortcut)||/^\d+$/.test(shortcut))fail('Ký tự tắt tối đa 40 ký tự, không chứa khoảng trắng hoặc chỉ gồm số.');
 if(shortcut&&all('templates').some(t=>t.id!==old?.id&&key(t.shortcut)===key(shortcut)))fail('Ký tự tắt đã tồn tại.');
 if(input.topicId&&!get('quick_reply_topics',input.topicId))fail('Chủ đề không tồn tại.');
 if(!Array.isArray(input.blocks)||!input.blocks.length||input.blocks.length>10)fail('Cần từ 1 đến 10 nhóm nội dung.');
 let total=0;const blocks=input.blocks.map(b=>{
  const text=String(b.text||'').trim();if(text.length>5000)fail('Mỗi nội dung tối đa 5000 ký tự.');
  if(!Array.isArray(b.assetIds||[])||(b.assetIds||[]).length>10)fail('Mỗi nội dung tối đa 10 tệp.');
  const assetIds=[...new Set(b.assetIds||[])];total+=assetIds.length;
  for(const id of assetIds){const a=get('assets',id);if(!a||a.active===false||!(a.scopes||['template']).includes('template')||!(a.scopes||['chat']).includes('chat'))fail('Tệp không còn được dùng cho tin nhắn nhanh.');if(a.connectionId)assertChannel(user,a.connectionId);}
  const contactIds=b.contactIds||[];if(!Array.isArray(contactIds)||contactIds.length>10||new Set(contactIds).size!==contactIds.length)fail('Tối đa 10 danh bạ khác nhau mỗi nội dung.');
  for(const id of contactIds){const c=get('conversations',id);if(!c||c.deletedAt||c.threadType===1||!c.externalUserId||!c.isFriend)fail('Danh bạ phải là bạn bè cá nhân.');assertChannel(user,c.connectionId);}
  if(!text&&!assetIds.length&&!contactIds.length)fail('Nhập văn bản, tệp hoặc danh bạ cho mỗi nội dung.');
  return {text,assetIds,contactIds};
 });if(total>100)fail('Tối đa 100 tệp trong một mẫu.');
 return {...old,name:required(input.name||blocks.find(b=>b.text)?.text.slice(0,80)||'Tin nhắn nhanh','Tên mẫu',200),shortcut,topicId:input.topicId||'',sortOrder:order(input.sortOrder),blocks,text:blocks.map(b=>b.text).filter(Boolean).join('\n\n')||'[Tệp / danh bạ]',assetIds:[],enabled:input.enabled!==false,usageInstructions:String(input.usageInstructions??old?.usageInstructions??'').slice(0,5000)};
}
const columns=['STT','Tên mẫu','Ký tự tắt','Chủ đề','Màu chủ đề','Nhóm nội dung','Nội dung','Mã tệp (;)', 'Mã danh bạ (;)','Bật'];
async function exportBook(sample=false){const book=new ExcelJS.Workbook(),s=book.addWorksheet('Tin nhan nhanh');s.columns=columns.map((header,i)=>({header,width:[8,28,16,24,18,16,75,35,35,12][i]}));s.views=[{state:'frozen',ySplit:1}];s.autoFilter='A1:J1';const rows=sample?[{name:'Chào khách',shortcut:'chao',sortOrder:1,blocks:[{text:'Xin chào {{name}}, mình có thể hỗ trợ gì cho bạn?'}]}]:all('templates');for(const t of rows){const topic=t.topicId?get('quick_reply_topics',t.topicId):null;(t.blocks||[{text:t.text,assetIds:t.assetIds}]).map((b,i)=>({...b,assetIds:b.assetIds??(i===0?t.assetIds||[]:[])})).forEach((b,i)=>s.addRow([t.sortOrder||1,t.name,t.shortcut||'',topic?.name||'',topic?.color||'',i+1,b.text||'',(b.assetIds||[]).join(';'),(b.contactIds||[]).join(';'),t.enabled===false?'Không':'Có']));}s.getRow(1).font={bold:true};s.eachRow(r=>r.alignment={vertical:'top',wrapText:true});const g=book.addWorksheet('Huong dan');g.columns=[{width:110}];for(const text of ['Mỗi dòng là một nhóm nội dung. Các dòng cùng Tên mẫu ghép thành một mẫu theo Nhóm nội dung.','Giữ nguyên tiêu đề. STT và Nhóm nội dung là số nguyên dương. Tối đa 10 nhóm/mẫu, 1000 dòng, file 1 MB.','Mã tệp và danh bạ tham chiếu dữ liệu hiện có trong hệ thống, ngăn cách bởi dấu ;. Không nhúng ảnh vào Excel.','Có thể dùng {{name}} để điền tên khách. Ký tự tắt không trùng và không chỉ gồm số.','Nhập chỉ thêm mẫu mới; tên/shortcut trùng được bỏ qua. Các dòng lỗi phải được sửa trước khi nhập.','Màu chủ đề dạng #RRGGBB. Không nhập công thức.'])g.addRow([text]);return {filename:sample?'mau-tin-nhan-nhanh.xlsx':'tin-nhan-nhanh.xlsx',file:Buffer.from(await book.xlsx.writeBuffer()).toString('base64')};}
async function preview(input,user){
 if(typeof input.file!=='string'||input.file.length>1400000||!/^[A-Za-z0-9+/]*={0,2}$/.test(input.file))fail('Chọn file .xlsx tối đa 1 MB.');const bytes=Buffer.from(input.file,'base64');if(bytes.length>1048576)fail('File vượt 1 MB.');
 // Bound uncompressed ZIP size before ExcelJS parses it.
 let end=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(bytes.readUInt32LE(i)===0x06054b50){end=i;break;}if(end<0)fail('File Excel không hợp lệ.');let at=bytes.readUInt32LE(end+16),size=0;const count=bytes.readUInt16LE(end+10);if(count>1000)fail('File Excel quá lớn.');for(let i=0;i<count;i++){if(at+46>bytes.length||bytes.readUInt32LE(at)!==0x02014b50)fail('File Excel không hợp lệ.');size+=bytes.readUInt32LE(at+24);if(size>20*1024*1024)fail('File giải nén vượt 20 MB.');at+=46+bytes.readUInt16LE(at+28)+bytes.readUInt16LE(at+30)+bytes.readUInt16LE(at+32);}
 const book=new ExcelJS.Workbook();try{await book.xlsx.load(bytes);}catch{fail('Không đọc được Excel.');}const s=book.getWorksheet('Tin nhan nhanh');if(!s||s.rowCount>1001)fail('Thiếu sheet Tin nhan nhanh hoặc quá 1000 dòng.');const cell=(r,i)=>{const c=r.getCell(i);if(c.type===ExcelJS.ValueType.Formula||typeof c.value==='object'&&c.value!==null)throw Error('Không hỗ trợ công thức hoặc ô dữ liệu phức tạp.');return String(c.value??'').trim();};if(columns.some((v,i)=>cell(s.getRow(1),i+1)!==v))fail('Tiêu đề không đúng. Hãy tải file mẫu.');const groups=new Map(),errors=[];
 for(let n=2;n<=s.rowCount;n++)try{const v=columns.map((_,i)=>cell(s.getRow(n),i+1));if(v.every(x=>!x))continue;const [stt,name,shortcut,topic,color,index,text,assets,contacts,on]=v;if(!name)throw Error('Thiếu tên mẫu.');if(color&&!/^#[\da-f]{6}$/i.test(color))throw Error('Màu chủ đề không hợp lệ.');if(on&&!['có','không','co','khong'].includes(key(on)))throw Error('Bật chỉ nhận Có/Không.');const meta={name,shortcut,sortOrder:order(stt),topic,color:color||'#1890ff',enabled:!['không','khong'].includes(key(on))};let group=groups.get(key(name));if(group&&JSON.stringify(group.meta)!==JSON.stringify(meta))throw Error('Các nhóm cùng mẫu phải có cùng STT, ký tự tắt và chủ đề.');if(!group){group={meta,rows:[],parts:[]};groups.set(key(name),group);}const idx=order(index);if(group.parts.some(p=>p.idx===idx))throw Error('Nhóm nội dung bị trùng.');group.rows.push(n);group.parts.push({idx,text,assetIds:assets.split(';').filter(Boolean),contactIds:contacts.split(';').filter(Boolean)});}catch(e){errors.push({row:n,status:'error',error:e.message});}
 const rows=[],seen=new Set();for(const g of groups.values()){const {topic,color,...t}=g.meta;t.blocks=g.parts.sort((a,b)=>a.idx-b.idx).map(({idx,...b})=>b);let error='',status='ready';try{const duplicate=all('templates').some(x=>key(x.name)===key(t.name)||t.shortcut&&key(x.shortcut)===key(t.shortcut));if(duplicate){status='duplicate';error='Mẫu đã có, bỏ qua';}else{if(t.shortcut&&seen.has(key(t.shortcut)))throw Error('Ký tự tắt trùng trong file.');validateQuickReply(t,user);if(t.shortcut)seen.add(key(t.shortcut));}}catch(e){status='error';error=e.message;}rows.push({...t,topic,color,row:g.rows[0],status,error});}rows.push(...errors);return {rows,ready:rows.filter(r=>r.status==='ready').length,duplicates:rows.filter(r=>r.status==='duplicate').length,errors:rows.filter(r=>r.status==='error').length};
}
export async function quickReplyRoute(path,method,input,user){
 if(!path.startsWith('/api/quick-replies'))return;permission(user,'inbox');
 const excel=path.match(/^\/api\/quick-replies\/excel\/(sample|export|preview|import)$/);if(excel&&method==='POST'){const action=excel[1];if(['sample','export'].includes(action))return exportBook(action==='sample');const result=await preview(input,user);if(action==='preview')return result;if(result.errors)fail('Sửa các dòng lỗi trước khi nhập.');return transaction(()=>{let imported=0;for(const r of result.rows.filter(r=>r.status==='ready')){let topic=r.topic?all('quick_reply_topics').find(t=>key(t.name)===key(r.topic)):null;if(r.topic&&!topic)topic=put('quick_reply_topics',{name:r.topic,color:r.color,sortOrder:all('quick_reply_topics').length+1});put('templates',validateQuickReply({...r,topicId:topic?.id},user));imported++;}audit(user.id,'quick_replies_imported','library',{imported});return {imported,skipped:result.duplicates};});}
 const m=path.match(/^\/api\/quick-replies\/(topics|templates)(?:\/([^/]+))?$/);if(!m)fail('Thao tác không hỗ trợ.',404);const kind=m[1]==='topics'?'quick_reply_topics':'templates',old=m[2]?get(kind,m[2]):null;if(m[2]&&!old)fail('Không tìm thấy dữ liệu.',404);if(old&&input.version!==old.version)fail('Dữ liệu đã thay đổi, tải lại trước khi lưu.',409);
 if(method==='DELETE'){if(!old)fail('Chọn dữ liệu cần xóa.');if(kind==='quick_reply_topics'&&all('templates').some(t=>t.topicId===old.id))fail('Chủ đề đang được dùng. Đổi chủ đề của các mẫu trước khi xóa.');if(kind==='templates'&&all('chatbots').some(b=>(b.templateIds||[]).includes(old.id)))fail('Mẫu đang được dùng bởi chatbot. Bỏ liên kết trước khi xóa.');remove(kind,old.id);audit(user.id,'quick_reply_deleted',old.id);return {ok:true};}
 if(!['POST','PATCH'].includes(method))fail('Thao tác không hỗ trợ.');let next;if(kind==='templates')next=validateQuickReply(input,user,old);else{const name=required(input.name,'Tên chủ đề',80);if(all(kind).some(t=>t.id!==old?.id&&key(t.name)===key(name)))fail('Tên chủ đề đã có.');if(!/^#[\da-f]{6}$/i.test(input.color||''))fail('Chọn màu dạng #RRGGBB.');next={...old,name,color:input.color,sortOrder:order(input.sortOrder)};}const saved=put(kind,next,old?.version);audit(user.id,'quick_reply_saved',saved.id);return saved;
}
