import { put, now } from './store.mjs';
export function seed() {
 const date=(days,h=10)=>{const d=new Date(); d.setDate(d.getDate()+days);d.setHours(h,0,0,0);return d.toISOString();};
 const channels=[['facebook','Studio Mộc · Facebook'],['instagram','moc.studio'],['tiktok','Mộc kể chuyện'],['youtube','Studio Mộc'],['threads','moc.studio'],['zalo','Mộc · Zalo OA'],['facebook_personal','Facebook cá nhân'],['zalo_personal','Zalo cá nhân'],['x','Studio Mộc · X'],['blogger','Góc nhỏ của Mộc'],['devto','Mộc · DEV.to'],['reddit','Mộc · Reddit']];
 channels.forEach(([provider,name],i)=>put('connections',{id:`ch${i+1}`,provider,name,mode:'demo',status:'demo',accountId:'',color:['#1877F2','#C13584','#111827','#ef4444','#111827','#0068ff'][i%6]}));
 const products=[['p1','Bình giữ nhiệt Mộc','MOC-BINH-500',289000,165000,42,'Gia dụng','sage'],['p2','Túi canvas Everyday','MOC-TUI-01',159000,75000,68,'Phụ kiện','sand'],['p3','Sổ tay Daily Notes','MOC-SO-A5',89000,35000,120,'Văn phòng','lilac'],['p4','Ly gốm buổi sáng','MOC-LY-01',199000,110000,8,'Gia dụng','peach']];
 products.forEach(([id,name,sku,price,cost,stock,category,color])=>put('products',{id,name,sku,id_sp:sku,productType:'physical',price,cost,stock,reserved:0,category,color,weight:500,active:true,description:'Thiết kế tối giản, chăm chút từng chi tiết. Sản phẩm mẫu để trải nghiệm hệ thống.'}));
 const customers=[['c1','Nguyễn Minh Anh','0901234567','minhanh@example.com','VIP','12 Nguyễn Văn Cừ, TP. Hồ Chí Minh'],['c2','Trần Hoàng Nam','0912345678','hoangnam@example.com','Khách mới','25 Lê Lợi, TP. Hồ Chí Minh'],['c3','Lê Thu Hà','0934567890','thuha@example.com','Khách quay lại','8 Trần Phú, Hà Nội'],['c4','Phạm Bảo Ngọc','0987654321','','Tiềm năng','Đà Nẵng']];
 customers.forEach(([id,name,phone,email,tag,address])=>put('customers',{id,customer_id:'LOCAL-'+id,name,phone,email,tags:[tag],address,consent:false,note:'Dữ liệu mẫu — không phải khách hàng thực.',stage:'consulting'}));
 const contents=[['ct1','Một chút xanh cho ngày mới','Chiếc bình bạn mang theo mỗi ngày cũng có thể kể một câu chuyện. 🌿\nNhẹ nhàng hơn, bền vững hơn cùng Mộc.\n#StudioMoc #SongXanh #EverydayEssentials','video','sage',1],['ct2','Trong túi mình hôm nay có gì?','Một chiếc túi nhỏ, cả thế giới của bạn.\nKhám phá túi canvas Everyday tại Mộc. #MocStudio #EverydayBag','image','sand',0],['ct3','3 thói quen nhỏ để bắt đầu ngày mới','Bắt đầu bằng một trang giấy mới, một tách trà ấm và một chút thời gian cho mình. #DailyNotes #SongCham','video','lilac',2],['ct4','Góc làm việc, nguồn cảm hứng mới','Những điều giản dị làm nên một ngày thật đẹp. #Workspace #MocStudio','image','peach',3]];
 contents.forEach(([id,title,caption,type,color,days],i)=>{put('contents',{id,title,caption,type,color,assets:[],channels:['ch1','ch2',i%2?'ch5':'ch3'],status:i===3?'draft':'scheduled',scheduleAt:date(days,19),campaignId:'camp1',productId:`p${i+1}`,variants:{},approval:'approved'}); if(i<3) ['ch1','ch2',i%2?'ch5':'ch3'].forEach(connectionId=>put('publications',{contentId:id,connectionId,title,caption,type,assets:[],status:'scheduled',scheduleAt:date(days,19),attempts:0,mode:'demo',revision:1}));});
 put('campaigns',{id:'camp1',name:'Chạm vào những điều giản dị',description:'Bộ sưu tập Everyday · Tháng này',color:'sage',status:'active',budget:3000000});
 const convs=[['cv1','c1','ch1','Bình này có giữ lạnh được qua đêm không shop?','comment','p1',5],['cv2','c2','ch2','Mình muốn đặt 2 túi màu tự nhiên ạ.','message','p2',15],['cv3','c3','ch6','Shop kiểm tra giúp mình đơn hàng nhé.','message','p3',35],['cv4','c4','ch1','Có giao hàng đến Đà Nẵng không shop?','comment','p4',70]];
 convs.forEach(([id,customerId,connectionId,text,kind,productId,min])=>{put('conversations',{id,customerId,connectionId,kind,status:'open',unread:true,assignee:'',productId,contentId:'ct1',lastMessage:text,lastAt:new Date(Date.now()-min*60000).toISOString(),tags:min===5?['Hỏi sản phẩm']:['Tư vấn'],mode:'demo'});put('messages',{conversationId:id,direction:'incoming',text,status:'demo',createdAt:new Date(Date.now()-min*60000).toISOString()});});
 put('templates',{name:'Chào khách',text:'Chào {{name}}, Mộc rất vui được hỗ trợ bạn. Bạn đang quan tâm sản phẩm nào ạ?'});
 put('templates',{name:'Xác nhận thông tin',text:'Bạn cho Mộc xin tên, số điện thoại và địa chỉ nhận hàng để lên đơn nhé.'});
 put('knowledge',{title:'Giới thiệu thương hiệu',body:'Mộc là thương hiệu phong cách sống tối giản. Giọng văn ấm áp, rõ ràng; xưng Mộc và bạn. Không tự hứa thời gian giao hàng hoặc tính năng sản phẩm chưa được xác nhận.'});
 put('knowledge',{title:'Chính sách mẫu',body:'Đây là dữ liệu trải nghiệm. Chủ cửa hàng cần cập nhật chính sách đổi trả và vận chuyển thực tế trước khi sử dụng AI với khách hàng.'});
 put('workflows',{name:'Phân loại khách hỏi giá',trigger:'message_received',keyword:'giá',action:'tag',value:'Hỏi giá',enabled:true,runs:0});
 put('workflows',{name:'Nhắc xử lý giao hàng thất bại',trigger:'shipping_failed',keyword:'',action:'notify',value:'Liên hệ khách để hỗ trợ giao lại',enabled:true,runs:0});
 put('orders',{id:'ord_sample1',code:'MOC-1001',customerId:'c3',items:[{productId:'p3',name:'Sổ tay Daily Notes',sku:'MOC-SO-A5',quantity:2,price:89000}],subtotal:178000,discount:0,shippingFee:25000,total:203000,paid:0,status:'draft',paymentStatus:'unpaid',address:'8 Trần Phú, Hà Nội',phone:'0934567890',note:'Đơn mẫu — chưa giữ tồn, chưa gửi vận chuyển.',source:'Zalo OA',createdAt:now()});
 put('notifications',{title:'Chào mừng đến với Mộc Workspace',body:'Bạn đang xem dữ liệu mẫu. Các kênh mẫu không gửi bài hay tin nhắn ra bên ngoài.',route:'settings',read:false});
}
