import { all,get,put,transaction,audit,now,notification,db } from './store.mjs';
import { fail,permission,required,number,reply } from './domain.mjs';

export const stages={MOI:'Khách mới',DA_CALL:'Đã call tư vấn',DONG_TIEN:'Đã đóng đủ tiền',DANG_HOC:'Đang tham gia học',SAP_HET_HAN:'Sắp hết hạn học',DA_XONG:'Đã học xong'};
export const leadStages=['NEW','CONTACTING','QUALIFIED','WON','LOST'];
export const extraKinds=['leads','journeys','courses','enrollments','journey_events','identities','tags','teams','team_members','channel_teams','master_video_tasks','customer_tasks','attendance_logs','payment_orders','sync_runs','template_runs','plan_handoffs','chat_reminders'];
export function normalizePhone(value){let s=String(value||'').replace(/[^\d+]/g,'');if(s.startsWith('+84'))s='0'+s.slice(3);else if(s.startsWith('84')&&s.length===11)s='0'+s.slice(2);return /^0[35789]\d{8}$/.test(s)?s:null;}
export function phonesIn(text){return [...new Set((String(text).match(/(?:\+84|84|0)[\s.-]*[35789](?:[\s.-]*\d){8}(?!\d)/g)||[]).map(normalizePhone).filter(Boolean))];}
export function permittedChannels(user){if(['owner','manager'].includes(user.role))return null;const teams=all('team_members').filter(m=>m.userId===user.id).map(m=>m.teamId);return new Set(all('channel_teams').filter(m=>teams.includes(m.teamId)).map(m=>m.connectionId));}
export function assertChannel(user,id){const allowed=permittedChannels(user);if(allowed&&!allowed.has(id))fail('Kênh này chưa được phân công cho nhóm của bạn.',403);}
export function scopeState(state,user){const allowed=permittedChannels(user);if(!allowed)return state;state.assets=state.assets.filter(a=>!a.connectionId||allowed.has(a.connectionId));state.connections=state.connections.filter(c=>allowed.has(c.id));state.conversations=state.conversations.filter(c=>allowed.has(c.connectionId));const convs=new Set(state.conversations.map(c=>c.id));const customers=new Set(state.conversations.map(c=>c.customerId));for(const c of state.customers.filter(c=>c.createdBy===user.id))customers.add(c.id);for(const c of state.journeys||[])if(c.assignee===user.id)customers.add(c.customerId);
 state.chat_reminders=(state.chat_reminders||[]).filter(r=>convs.has(r.conversationId));state.template_runs=(state.template_runs||[]).filter(r=>convs.has(r.conversationId));state.messages=state.messages.filter(m=>convs.has(m.conversationId));state.customers=state.customers.filter(c=>customers.has(c.id));state.orders=state.orders.filter(o=>customers.has(o.customerId));const orders=new Set(state.orders.map(o=>o.id));for(const k of ['payments','returns','shipments','payment_orders'])state[k]=(state[k]||[]).filter(r=>orders.has(r.orderId));for(const k of ['leads','journeys','enrollments','identities','journey_events','plan_handoffs','chatPlanSummaries','savedPlanSummaries'])state[k]=(state[k]||[]).filter(r=>customers.has(r.customerId));state.publications=state.publications.filter(p=>allowed.has(p.connectionId));state.contents=state.contents.filter(c=>(c.channels||[]).every(id=>allowed.has(id))&&(c.channels||[]).length);state.notifications=[];state.sync_runs=[];state.master_video_tasks=[];state.customer_tasks=[];state.attendance_logs=[];return state;}
export function assertCustomer(user,id){if(['owner','manager'].includes(user.role)||get('customers',id)?.createdBy===user.id)return;const allowed=permittedChannels(user);if(!all('conversations').some(c=>c.customerId===id&&allowed.has(c.connectionId))&&!all('journeys').some(j=>j.customerId===id&&j.assignee===user.id))fail('Khách hàng chưa được phân công cho bạn.',403);}

export function migrateLocal(){if(db.prepare('SELECT version FROM migrations WHERE version=2').get())return;transaction(()=>{for(const c of all('customers'))if(!c.customer_id)put('customers',{...c,customer_id:'LOCAL-'+c.id});for(const p of all('products'))put('products',{...p,id_sp:p.id_sp||p.sku,productType:p.productType||'physical'});for(const [i,name] of ['Cần tư vấn','Đã gọi','Quan tâm khóa học','Chờ thanh toán','Học viên','Ưu tiên','Gửi giáo trình','Chăm sóc lại'].entries())put('tags',{id:'tag-'+i,name,color:['#dcebdc','#e7dff5','#dce9f5','#f7e8c9'][i%4],row:i<4?1:2});db.prepare('INSERT INTO migrations VALUES(2,?)').run(now());});}

// Never infer identity from a matching telephone alone. Offer explicit review instead.
export function captureLead(conv,msg){const p=get('customers',conv.customerId),phones=phonesIn(msg.text);if(conv.threadType!==1&&msg.direction==='incoming'&&p&&!p.phone&&phones.length===1){put('customers',{...p,phone:phones[0],phoneDetectedFrom:msg.id});}for(const phone of phonesIn(msg.text)){if(all('leads').some(l=>l.phone===phone&&l.conversationId===conv.id))continue;const candidates=all('customers').filter(c=>normalizePhone(c.phone||c.sdt)===phone).map(c=>c.id);const agents=db.prepare("SELECT id,role FROM users WHERE active=1 AND role IN ('support','manager') ORDER BY id").all().filter(u=>{const channels=permittedChannels(u);return channels===null||channels.has(conv.connectionId);});const lead=put('leads',{name:get('customers',conv.customerId)?.name||'Khách mới',phone,customerId:conv.customerId,conversationId:conv.id,connectionId:conv.connectionId,postId:conv.postId||null,commentId:conv.externalCommentId||null,stage:'NEW',assignee:agents.length?agents[all('leads').length%agents.length].id:'',candidateCustomerIds:candidates,source:conv.kind==='comment'?'Bình luận':'Tin nhắn'});notification('Lead mới từ '+lead.source,phone,'leads');}const current=get('conversations',conv.id);if(current)put('conversations',{...current,waitingSince:current.waitingSince||now(),slaAlerted:false});}
export function serviceTick(){const minutes=Number(get('settings','care')?.slaMinutes||3);for(const c of all('conversations'))if(c.waitingSince&&c.status!=='resolved'&&!c.slaAlerted&&Date.now()-Date.parse(c.waitingSince)>minutes*60000){notification('Quá hạn phản hồi',`${get('customers',c.customerId)?.name||'Khách hàng'} · ${minutes} phút`,'inbox');put('conversations',{...c,slaAlerted:true});}for(const j of all('journeys'))if(j.stage==='DANG_HOC'&&j.endDate){const days=Math.ceil((Date.parse(j.endDate+'T23:59:59+07:00')-Date.now())/86400000);if(days<=7&&days>=0){put('journeys',{...j,stage:'SAP_HET_HAN'});put('journey_events',{customerId:j.customerId,from:'DANG_HOC',to:'SAP_HET_HAN',reason:'Còn tối đa 7 ngày',actor:'system'});notification('Học viên sắp hết hạn',get('customers',j.customerId)?.name||j.customerId,'students');}}}
export function planFor(customer,masters,custom){return (customer.is_customized?custom.filter(t=>t.customer_id===customer.customer_id&&!t.is_deleted):masters.filter(t=>t.video_date===customer.video_date&&(!customer.ma_vd||t.nhom===customer.ma_vd))).sort((a,b)=>(a.day-b.day)||((a.sort_order||0)-(b.sort_order||0)));}
export function ingestComments(channel,entries){for(const entry of entries||[]){if(String(entry.id)!==String(channel.accountId))continue;for(const change of entry.changes||[]){const v=change.value;if(change.field!=='feed'||v?.item!=='comment'||!v.comment_id)continue;const eventKey=channel.id+':comment:'+v.comment_id+':'+v.verb+':'+(v.created_time||entry.time||'');if(db.prepare('SELECT id FROM events WHERE id=?').get(eventKey))continue;db.prepare('INSERT INTO events VALUES(?,?,?,?)').run(eventKey,channel.id,now(),JSON.stringify(change));let conv=all('conversations').find(c=>c.connectionId===channel.id&&c.externalCommentId===v.comment_id);
 if(v.verb==='remove'){if(conv)put('conversations',{...conv,status:'resolved',remoteDeleted:true});continue;}if(!['add','edited'].includes(v.verb)||!v.message||String(v.from?.id)===String(channel.accountId))continue;
 if(!conv){const external=String(v.from?.id||'');let identity=external?all('identities').find(i=>i.connectionId===channel.id&&i.externalUserId===external):null;let customer=identity?get('customers',identity.customerId):null;if(!customer){customer=put('customers',{name:v.from?.name||'Khách từ bình luận',customer_id:'LOCAL-COMMENT-'+v.comment_id,phone:'',tags:[],consent:false});if(external)put('identities',{customerId:customer.id,connectionId:channel.id,externalUserId:external});}conv=put('conversations',{customerId:customer.id,connectionId:channel.id,externalUserId:external,externalCommentId:v.comment_id,postId:v.post_id,kind:'comment',mode:'api',status:'open',tags:[]});}
 const previous=all('messages').find(m=>m.conversationId===conv.id&&m.externalId===v.comment_id);const msg=put('messages',{...previous,conversationId:conv.id,externalId:v.comment_id,direction:'incoming',text:String(v.message).slice(0,30000),status:'received',edited:v.verb==='edited'});put('conversations',{...conv,lastMessage:msg.text,lastAt:now(),unread:true,status:'open'});captureLead(get('conversations',conv.id),msg);
 }}}
export function journeyUpdate(user,id,input){permission(user,'customers');assertCustomer(user,id);const c=get('customers',id);if(!c)fail('Không tìm thấy khách.',404);const prev=all('journeys').find(j=>j.customerId===id);if(!stages[input.stage])fail('Giai đoạn không hợp lệ.');if(prev&&input.version!==prev.version)fail('Hành trình đã thay đổi.',409);const paid=all('orders').some(o=>o.customerId===id&&o.status!=='cancelled'&&o.paid>=o.total&&o.total>0)||all('enrollments').some(e=>e.customerId===id&&e.paymentVerified===true);
 if(['DONG_TIEN','DANG_HOC','SAP_HET_HAN','DA_XONG'].includes(input.stage)&&!paid)fail('Cần đơn đã thu đủ hoặc ghi danh đã đối soát thanh toán.');const startDate=input.startDate||prev?.startDate||'',endDate=input.endDate||prev?.endDate||'';if(['DANG_HOC','SAP_HET_HAN'].includes(input.stage)&&(!/^\d{4}-\d{2}-\d{2}$/.test(startDate)||!/^\d{4}-\d{2}-\d{2}$/.test(endDate)||endDate<startDate))fail('Nhập ngày bắt đầu và kết thúc hợp lệ.');if(input.assignee&&!db.prepare('SELECT id FROM users WHERE id=? AND active=1').get(input.assignee))fail('Người phụ trách không hợp lệ.');return transaction(()=>{const r=put('journeys',{...prev,customerId:id,stage:input.stage,startDate,endDate,assignee:input.assignee||'',note:String(input.note||'').slice(0,2000)});put('journey_events',{customerId:id,from:prev?.stage||'MOI',to:r.stage,actor:user.id,reason:input.note||'',assignee:r.assignee});audit(user.id,'journey_changed',id,{from:prev?.stage,to:r.stage});notification('Cập nhật hành trình',`${c.name} → ${stages[r.stage]}`,'students');return r;});}
export function syncPaymentOrder(order){const customer=get('customers',order.customerId);const prev=all('payment_orders').find(p=>p.orderId===order.id);return put('payment_orders',{...prev,orderId:order.id,customer_id:customer.customer_id||'LOCAL-'+customer.id,order_payload:{source:'omnichannel_local',order_code:order.code,status:order.status,total:order.total,paid:order.paid,payment_status:order.paymentStatus,items:order.items.map(i=>({id_sp:get('products',i.productId)?.id_sp||i.sku,ten_sp:i.name,so_luong:i.quantity,don_gia:i.price,thanh_tien:i.price*i.quantity,course_id:i.courseId||null})),conversation_id:order.conversationId||null}});}
export function enrollmentFromOrder(order){const verified=order.paid>=order.total&&order.total>0&&order.status!=='cancelled';for(const old of all('enrollments').filter(e=>e.orderId===order.id))if(old.paymentVerified!==verified)put('enrollments',{...old,paymentVerified:verified,status:verified?'pending_start':'payment_review'});if(!verified)return;for(const i of order.items.filter(i=>i.productType==='course'))if(!all('enrollments').some(e=>e.orderId===order.id&&e.productId===i.productId))put('enrollments',{customerId:order.customerId,courseId:i.courseId||null,productId:i.productId,orderId:order.id,name:i.name,paymentVerified:true,status:'pending_start'});}

const runningConversations=new Set();
export async function runTemplate(user,conversationId,input){permission(user,'inbox');const conv=get('conversations',conversationId);if(!conv)fail('Không tìm thấy hội thoại.',404);assertChannel(user,conv.connectionId);if(runningConversations.has(conversationId))fail('Hội thoại đang gửi chuỗi mẫu.',409);let run=input.runId?get('template_runs',input.runId):null;if(input.runId&&(!run||run.conversationId!==conversationId||run.status!=='failed'))fail('Chỉ tiếp tục chuỗi thất bại rõ ràng tại hội thoại này.');
 if(!run){const template=get('templates',input.templateId);if(!template)fail('Không tìm thấy mẫu.');const name=get('customers',conv.customerId)?.name||'bạn';const blocks=(template.blocks||[{text:template.text}]).map(b=>({text:required(b.text,'Khối văn bản',5000).replaceAll('{{name}}',name)}));run=put('template_runs',{conversationId,templateId:template.id,blocks,assetIds:template.assetIds||[],nextIndex:0,status:'pending',actor:user.id});}
 runningConversations.add(conversationId);try{for(let i=run.nextIndex;i<run.blocks.length;i++){run=put('template_runs',{...run,nextIndex:i,status:'sending'});try{const msg=await reply(user,conversationId,{text:run.blocks[i].text,assetIds:i===0?run.assetIds||[]:[],version:get('conversations',conversationId).version});run=put('template_runs',{...run,nextIndex:i+1,status:'pending',messageIds:[...(run.messageIds||[]),msg.id]});}catch(e){run=put('template_runs',{...run,status:e.unknown?'unknown':'failed',error:e.message});return run;}}return put('template_runs',{...run,status:'done',error:''});}finally{runningConversations.delete(conversationId);}}

export async function careRoute(path,method,input,user){
 const sequence=path.match(/^\/api\/care\/conversations\/([^/]+)\/template$/);if(sequence&&method==='POST')return runTemplate(user,sequence[1],input);
 if(path==='/api/care/templates'&&method==='POST'){permission(user,'inbox');if(!Array.isArray(input.blocks)||input.blocks.length<1||input.blocks.length>10)fail('Cần từ 1 đến 10 khối.');const shortcut=required(input.shortcut,'Phím tắt',40).replace(/^\//,'');if(!/^[a-z0-9_-]+$/i.test(shortcut))fail('Phím tắt chỉ gồm chữ, số, gạch ngang.');if(all('templates').some(t=>t.shortcut===shortcut))fail('Phím tắt đã tồn tại.');const blocks=input.blocks.map(b=>({text:required(b.text,'Khối văn bản',5000)}));return put('templates',{name:required(input.name,'Tên mẫu',200),shortcut,blocks,text:blocks.map(b=>b.text).join('\n\n')});}
 if(path==='/api/care/config'&&method==='POST'){if(user.role!=='owner')fail('Cần quyền chủ hệ thống.',403);return put('settings',{id:'care',slaMinutes:number(input.slaMinutes,'SLA',1,120)});}
 if(path==='/api/care/tags'&&method==='POST'){if(!['owner','manager'].includes(user.role))fail('Cần quyền quản lý.',403);if(!/^#[0-9a-f]{6}$/i.test(input.color))fail('Màu không hợp lệ.');return put('tags',{...(input.id?get('tags',input.id):{}),name:required(input.name,'Tên nhãn',40),row:number(input.row,'Hàng',1,2),color:input.color});}
 if(path==='/api/care/teams'&&method==='POST'){if(user.role!=='owner')fail('Cần quyền chủ hệ thống.',403);if(!Array.isArray(input.userIds)||!Array.isArray(input.connectionIds))fail('Chọn thành viên và kênh.');for(const id of input.userIds)if(!db.prepare('SELECT id FROM users WHERE id=? AND active=1').get(id))fail('Thành viên không hợp lệ.');for(const id of input.connectionIds)if(!get('connections',id))fail('Kênh không hợp lệ.');return transaction(()=>{const team=put('teams',{name:required(input.name,'Tên nhóm',100)});for(const userId of new Set(input.userIds))put('team_members',{teamId:team.id,userId});for(const connectionId of new Set(input.connectionIds))put('channel_teams',{teamId:team.id,connectionId});audit(user.id,'team_created',team.id);return team;});}
 const lead=path.match(/^\/api\/care\/leads\/([^/]+)$/);if(lead&&method==='PATCH'){permission(user,'customers');const l=get('leads',lead[1]);if(!l)fail('Không tìm thấy lead.',404);assertCustomer(user,l.customerId);if(!leadStages.includes(input.stage))fail('Trạng thái lead không hợp lệ.');if(input.stage==='LOST')required(input.reason,'Lý do mất lead',500);if(input.stage==='WON'&&!all('orders').some(o=>o.customerId===l.customerId&&o.status!=='draft'&&o.status!=='cancelled'))fail('Cần đơn được xác nhận để đánh dấu chuyển đổi.');return put('leads',{...l,stage:input.stage,reason:input.reason||''},input.version);}
 const journey=path.match(/^\/api\/care\/customers\/([^/]+)\/journey$/);if(journey&&method==='POST')return journeyUpdate(user,journey[1],input);
 const plan=path.match(/^\/api\/care\/customers\/([^/]+)\/plan$/);if(plan&&method==='GET'){assertCustomer(user,plan[1]);const c=get('customers',plan[1]);if(!c)fail('Không tìm thấy.',404);return {customer_id:c.customer_id,mode:c.is_customized?'custom':'master',tasks:planFor(c,all('master_video_tasks'),all('customer_tasks')).map(({id,day,type,title,detail,nhom,sort_order})=>({id,day,type,title,detail,nhom,sort_order})),attendance:all('attendance_logs').filter(a=>a.customer_id===c.customer_id).map(({access_date})=>({access_date}))};}
 if(path==='/api/care/courses'&&method==='POST'){permission(user,'products');const course=put('courses',{name:required(input.name,'Tên khóa học',200),fee:number(input.fee,'Học phí'),duration:required(input.duration,'Thời lượng',100),status:1,description:String(input.description||'').slice(0,5000)});put('products',{name:course.name,sku:'COURSE-'+course.id,id_sp:'COURSE-'+course.id,price:course.fee,cost:0,stock:0,reserved:0,weight:0,active:true,productType:'course',courseId:course.id});return course;}
 return undefined;
}
