import {createRequire} from 'node:module';
import {spawn,execFileSync} from 'node:child_process';
import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs';
import {resolve,join} from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
mkdirSync('test-data',{recursive:true});mkdirSync('test-results',{recursive:true});
const env={...process.env,PORT:'4406',DATA_DIR:mkdtempSync(join(resolve('test-data'),'chat-ui-'))},base='http://127.0.0.1:4406';
const server=spawn(process.execPath,['server/index.mjs'],{env,stdio:'pipe',windowsHide:true});let browser;
try{
 for(let i=0;i<80;i++){try{await fetch(base+'/api/health');break;}catch{await new Promise(r=>setTimeout(r,100));}}
 browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.getByLabel('Tên của bạn',{exact:true}).fill('Chat QA');await page.getByLabel('Email',{exact:true}).fill('chat-qa@example.test');await page.getByLabel('Mật khẩu (tối thiểu 10 ký tự)',{exact:true}).fill('ChatUITest2026!');await page.getByRole('button',{name:'Tạo không gian làm việc'}).click();await page.locator('.sidebar').waitFor();
 execFileSync(process.execPath,['--input-type=module','-e',`const {put,db}=await import('./server/store.mjs');const user=db.prepare('SELECT id FROM users LIMIT 1').get().id;put('connections',{id:'demo',name:'Zalo kiểm thử',provider:'zalo_personal',mode:'demo',status:'connected'});for(const [id,name,phone] of [['p1','Khách kiểm thử Mai','0900000001'],['p2','Nhóm Học viên QA','']])put('customers',{id,name,phone,tags:[]});for(const [id,p,type] of [['c1','p1',0],['c2','p2',1]]){put('conversations',{id,customerId:p,connectionId:'demo',kind:'message',threadType:type,mode:'demo',status:'open',unread:false,tags:['Cần tư vấn'],lastMessage:'Tin nhắn kiểm thử',lastAt:new Date().toISOString(),group:type?{name:'Nhóm Học viên QA',memberCount:2,members:[{id:'u1',name:'Học viên QA',role:'member'},{id:'u2',name:'Giáo viên QA',role:'owner'}]}:null});put('messages',{id:'m-'+id,conversationId:id,direction:'incoming',status:'demo',senderName:'Học viên QA',text:'Tư vấn khóa học '+id+' https://example.com/course'});}put('templates',{id:'tpl',name:'Chào mừng QA',shortcut:'chaoqa',text:'Chào {{name}}, mình có thể hỗ trợ gì?'});`],{env,stdio:'pipe'});
 await page.goto(base+'/#inbox');await page.locator('[data-action="open-conversation"][data-id="c1"]').click();
 await page.locator('#reply-form textarea').fill('Bản nháp cá nhân');
 await page.locator('[data-action="open-conversation"][data-id="c2"]').click();await page.locator('#reply-form textarea').fill('Bản nháp nhóm');
 await page.locator('[data-action="open-conversation"][data-id="c1"]').click();assert.equal(await page.locator('#reply-form textarea').inputValue(),'Bản nháp cá nhân');
 await page.locator('[data-chat=templates]').click();await page.locator('#chat-template-search').fill('chaoqa');await page.locator('[data-chat=insert-template][data-id=tpl]').click();assert.match(await page.locator('#reply-form textarea').inputValue(),/Bản nháp cá nhân\nChào Khách kiểm thử Mai/);
 await page.locator('[data-chat=quote][data-id=m-c1]').click();await page.locator('.chat-draft-context .quote-block').waitFor();
 await page.locator('#reply-form textarea').fill('Trả lời có trích dẫn');await page.locator('#reply-form button[type=submit]').click();await page.locator('[data-message] .bubble').filter({hasText:'Trả lời có trích dẫn'}).waitFor();assert.equal(await page.locator('#reply-form textarea').inputValue(),'');
 await page.locator('[data-chat=choose-media]').click();await page.locator('#chat-upload').setInputFiles({name:'qa.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aPZsAAAAASUVORK5CYII=','base64')});await page.locator('.chat-draft-context').getByText(/qa.png/).waitFor();await page.locator('#reply-form button[type=submit]').click();await page.locator('.chat-attachment img').waitFor();
 await page.locator('[data-chat=pin-message][data-id=m-c1]').click();await page.locator('.chat-pins').waitFor();
 await page.locator('#chat-message-search').fill('không khớp nội dung');assert.equal(await page.locator('[data-message]:visible').count(),0);await page.locator('#chat-message-search').fill('');
 await page.locator('.chat-actions summary').click();await page.locator('[data-chat=assign]').click();await page.locator('#chat-assign-form input[name=assigneeIds]').first().check();await page.locator('#chat-assign-form button').click();await page.locator('.chat-assigned').waitFor();
 await page.locator('[data-chat=remind-message][data-id=m-c1]').click();await page.locator('#chat-reminder-form [name=title]').fill('Gọi chăm sóc QA');await page.locator('#chat-reminder-form [name=dueAt]').fill('2030-01-05T10:00');await page.locator('#chat-reminder-form button').click();await page.locator('[data-chat=all-reminders]').click();await page.getByText('Gọi chăm sóc QA',{exact:true}).waitFor();await page.locator('[data-chat=reminder-done]').click();await page.getByText('Chưa có nhắc chăm sóc.',{exact:true}).waitFor();await page.keyboard.press('Escape');
 await page.locator('[data-chat=filters]').click();await page.locator('#chat-filter-form [name=type]').selectOption('group');await page.locator('#chat-filter-form [name=phone]').selectOption('no');await page.locator('#chat-filter-form button[type=submit]').click();assert.equal(await page.locator('.conversation-item').count(),1);await page.locator('.conversation-item').click();assert.equal(await page.locator('#reply-form textarea').inputValue(),'Bản nháp nhóm');
 await page.locator('.chat-actions summary').click();await page.locator('[data-chat=group]').click();await page.locator('#chat-member-search').fill('Giáo viên');assert.equal(await page.locator('[data-member]:visible').count(),1);await page.keyboard.press('Escape');
 await page.locator('[data-chat=reset]').click();await page.locator('[data-chat=select-all]').click();await page.locator('[data-chat=bulk-read]').click();await page.locator('[data-chat=select-all]').waitFor();
 for(const width of [1440,390]){await page.setViewportSize({width,height:1000});if(width<760)await page.locator('[data-action=back-inbox]').click();await page.locator('[data-action="open-conversation"][data-id="c2"]').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.waitForFunction(()=>!document.querySelector('#toast-root')?.children.length);if(width<760){const send=page.locator('#reply-form button[type=submit]');await send.scrollIntoViewIfNeeded();const box=await send.boundingBox();assert.ok(box.y+box.height<925,'Composer send button must clear mobile navigation');}await page.screenshot({path:`test-results/chat-pancake-${width}.png`,fullPage:true});}
 await page.reload();await page.locator('[data-action="open-conversation"][data-id="c2"]').click();await page.locator('#reply-form').waitFor();assert.equal(await page.locator('#reply-form textarea').inputValue(),'Bản nháp nhóm');assert.deepEqual(errors,[]);
 writeFileSync('test-results/chat-ui-report.json',JSON.stringify({ok:true,widths:[1440,390],checks:['per-conversation drafts','template insert','quoted demo reply','message pin','search','assignment','reminder completion','combined filters','group members','bulk read','draft after reload'],errors},null,2));console.log('Chat UI: desktop/mobile, filters, drafts, quotes, assignment, reminders, groups and bulk actions passed.');
}finally{await browser?.close();server.kill();}
