import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs';
import {resolve,join} from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
mkdirSync('test-data',{recursive:true});mkdirSync('test-results',{recursive:true});
const dir=mkdtempSync(join(resolve('test-data'),'ui-'));const base='http://127.0.0.1:4401';
const server=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,PORT:'4401',DATA_DIR:dir},stdio:'pipe',windowsHide:true});let browser;const errors=[];
try{
 for(let i=0;i<80;i++){try{await fetch(base+'/api/health');break;}catch{await new Promise(r=>setTimeout(r,100));}}
 browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.getByLabel('Tên của bạn',{exact:true}).fill('Kiểm thử giao diện');await page.getByLabel('Email',{exact:true}).fill('ui@example.test');await page.getByLabel('Mật khẩu (tối thiểu 10 ký tự)',{exact:true}).fill('UITestPassword2026!');await page.getByRole('button',{name:'Tạo không gian làm việc'}).click();await page.waitForSelector('.sidebar');
 for(const route of ['dashboard','comments','inbox','leads','students','courses','integration','care-admin','reply-library','customers','orders','settings']){await page.goto(base+'/#'+route);await page.waitForSelector('#page h1');assert.ok(await page.locator('#page').innerText());await page.screenshot({path:'test-results/desktop-'+route+'.png',fullPage:true});}
 await page.goto(base+'/#reply-library');await page.getByRole('button',{name:'+ Mẫu nhiều khối'}).click();await page.getByLabel('Tên mẫu',{exact:true}).fill('Chuỗi UI');await page.getByLabel('Phím tắt',{exact:true}).fill('uitest');await page.locator('textarea[name=blocksText]').fill('Xin chào {{name}}\n---\nMời bạn tham khảo khóa học.');await page.locator('[data-care-form="sequence"] button[type=submit]').click();await page.getByRole('heading',{name:'Chuỗi UI',exact:true}).waitFor();await page.goto(base+'/#inbox');await page.locator('#reply-form textarea').fill('/uitest');await page.getByRole('button',{name:'/uitest · Chuỗi UI'}).click();await page.getByRole('button',{name:'Gửi chuỗi trả lời',exact:true}).click();await page.locator('.bubble').getByText('Mời bạn tham khảo khóa học.',{exact:true}).waitFor();
 await page.goto(base+'/#courses');await page.getByRole('button',{name:'+ Thêm khóa học'}).click();await page.getByLabel('Tên khóa học',{exact:true}).fill('Khóa học kiểm thử UI');await page.getByLabel('Học phí (₫)',{exact:true}).fill('1200000');await page.getByLabel('Thời lượng',{exact:true}).fill('30 ngày');await page.locator('[data-care-form="course"] button[type=submit]').click();await page.getByRole('heading',{name:'Khóa học kiểm thử UI'}).waitFor();
 await page.goto(base+'/#inbox');await page.getByRole('button',{name:'Tạo đơn',exact:true}).click();await page.locator('#care-product').selectOption({label:'Khóa học kiểm thử UI · 1.200.000 ₫ · Khóa học'});await page.locator('[data-care-form="inline-order"] input[name=phone]').fill('0901234567');await page.getByRole('button',{name:'Tạo đơn nháp',exact:true}).click();await page.getByText(/Đã tạo đơn nháp MOC-/).last().waitFor();await page.screenshot({path:'test-results/desktop-inchat-order.png',fullPage:true});

 await page.getByRole('button',{name:'Thông tin khách',exact:true}).click();await page.getByRole('button',{name:'Tạo phác đồ',exact:true}).click();const newFrame=page.frameLocator('.plan-editor-frame');await newFrame.getByText('PHÁC ĐỒ: TẠO MỚI',{exact:false}).waitFor();await newFrame.getByText('Tạo mới từ thông tin khách đang chat',{exact:false}).waitFor();await page.screenshot({path:'test-results/desktop-chat-new-plan.png',fullPage:true});await page.getByRole('button',{name:'← Trở lại cuộc trò chuyện',exact:true}).click();await page.locator('#reply-form').waitFor();
 const bootstrap=await page.request.get(base+'/api/bootstrap').then(r=>r.json());const headers={'X-CSRF-Token':bootstrap.user.csrf};
 const state=await page.request.get(base+'/api/state').then(r=>r.json());const courseOrder=state.orders.find(o=>o.items.some(i=>i.name==='Khóa học kiểm thử UI'));
 for(const body of [{action:'confirm'},{action:'pay',amount:courseOrder.total,reference:'UI xác nhận đã nhận chuyển khoản'}]){const r=await page.request.post(base+'/api/orders/'+courseOrder.id+'/action',{headers,data:body});assert.equal(r.status(),200,await r.text());}
 await page.request.post(base+'/api/taophacdo/import-json',{headers,data:{table:'master_video_tasks',preview:false,rows:[{id:'ui-master',video_date:'2026-10-01',nhom:'NHOM-UI',day:1,type:'Bài bắt buộc',title:'Bài tập UI từ phác đồ mẫu',detail:'Hướng dẫn đã kiểm tra',sort_order:0}]}});
 await page.goto(base+'/#phacdo');await page.getByRole('button',{name:'Tạo phác đồ',exact:true}).first().click();const frame=page.frameLocator('.plan-editor-frame');await frame.getByText('✓ Đã xác nhận nhận tiền',{exact:false}).waitFor();await frame.locator('select').filter({has:page.locator('option[value="2026-10-01|NHOM-UI"]')}).selectOption('2026-10-01|NHOM-UI');await frame.getByRole('button',{name:'Lưu',exact:true}).click();await frame.getByRole('button',{name:'Chỉnh sửa phác đồ',exact:true}).waitFor();await frame.getByRole('heading',{name:'Bài tập UI từ phác đồ mẫu'}).waitFor();await page.screenshot({path:'test-results/desktop-paid-plan.png',fullPage:true});const planState=await page.request.get(base+'/api/state').then(r=>r.json());assert.equal(planState.plan_handoffs.find(h=>h.orderId===courseOrder.id).status,'saved_local');
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(base);await mobile.getByLabel('Email',{exact:true}).fill('ui@example.test');await mobile.getByLabel('Mật khẩu',{exact:true}).fill('UITestPassword2026!');await mobile.getByRole('button',{name:/Đăng nhập/}).click();await mobile.waitForSelector('.sidebar');
 for(const route of ['dashboard','students','leads','courses','integration','inbox']){await mobile.goto(base+'/#'+route);await mobile.waitForSelector('#page h1');const overflow=await mobile.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1);assert.equal(overflow,false,'Page overflow on '+route);await mobile.screenshot({path:'test-results/mobile-'+route+'.png',fullPage:true});}
 await mobile.locator('.conversation-item').first().click();await mobile.getByRole('button',{name:'Hồ sơ / Đơn',exact:true}).click();await mobile.getByRole('button',{name:'Tạo đơn',exact:true}).click();await mobile.locator('#care-product').waitFor({state:'visible'});await mobile.screenshot({path:'test-results/mobile-inchat-order.png',fullPage:true});
 await mobile.goto(base+'/#phacdo');await mobile.getByRole('button',{name:'Mở phác đồ',exact:true}).first().click();const mf=mobile.frameLocator('.plan-editor-frame');await mf.getByRole('button',{name:'Lưu',exact:true}).waitFor();await mobile.screenshot({path:'test-results/mobile-paid-plan-editor.png',fullPage:true});assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await mf.getByRole('button',{name:'Lưu',exact:true}).click();await mf.getByRole('button',{name:'Chỉnh sửa phác đồ',exact:true}).waitFor();
 assert.deepEqual(errors,[]);writeFileSync('test-results/ui-report.json',JSON.stringify({ok:true,desktop:'1440x1000',mobile:'390x844',pageErrors:errors,checkedAt:new Date().toISOString()},null,2));console.log('UI checks passed: desktop, mobile, course creation, in-chat order, no page errors or body overflow.');
}finally{await browser?.close();server.kill();}
